-- Convertido desde db_scripts/16_08_2026/1.esquema_completo.sql
-- MySQL 8 — DecoCake Shop

USE `DecoCakeShop`;

SET FOREIGN_KEY_CHECKS = 0;

/* ============================================================================
   DECOCAKE SHOP — Importadora
   Esquema completo SQL Server (destructivo: recrea la BD de negocio)
   Fecha: 16/08/2026
   Convenciones (igual Academia 3.0):
     - Tablas/columnas MAYÚSCULAS
     - IDs VARCHAR(50) con prefijo
     - FECHA CHAR(8) DDMMYYYY | HORA CHAR(8) HH:MM:SS
     - Auditoría en tablas principales: CREADOPOR, FECHACREACION, HORACREACION,
       MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION
   ============================================================================ */

DROP PROCEDURE IF EXISTS usp_validate_user;
DROP FUNCTION IF EXISTS fn_fecha_ddmmyyyy;
DROP FUNCTION IF EXISTS fn_actor;

DROP TABLE IF EXISTS COTIZACION_PAGO;
DROP TABLE IF EXISTS COTIZACION_DETALLE;
DROP TABLE IF EXISTS VENTA_DETALLE;
DROP TABLE IF EXISTS VENTA;
DROP TABLE IF EXISTS COTIZACION;
DROP TABLE IF EXISTS PRODUCTO;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS UNIDAD;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS FORMA_PAGO;
DROP TABLE IF EXISTS TIPO_ENTREGA;
DROP TABLE IF EXISTS AUDITORIA;
DROP TABLE IF EXISTS USUARIO_SUBMODULO_EXCLUIDO;
DROP TABLE IF EXISTS GRUPO_SUBMODULO_EXCLUIDO;
DROP TABLE IF EXISTS USUARIO_MODULO_EXCLUIDO;
DROP TABLE IF EXISTS USUARIO_MODULO;
DROP TABLE IF EXISTS GRUPO_MODULO;
DROP TABLE IF EXISTS TIPO_PERMISO;
DROP TABLE IF EXISTS SUBMODULO;
DROP TABLE IF EXISTS MODULO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS TIPOUSUARIO;

DROP FUNCTION IF EXISTS fn_fecha_ddmmyyyy;

DELIMITER $$

CREATE FUNCTION fn_fecha_ddmmyyyy()
RETURNS CHAR(8)
DETERMINISTIC
NO SQL
BEGIN
    RETURN DATE_FORMAT(
        IFNULL(CONVERT_TZ(UTC_TIMESTAMP(), '+00:00', '-05:00'), DATE_SUB(UTC_TIMESTAMP(), INTERVAL 5 HOUR)),
        '%d%m%Y'
    );
END$$

DELIMITER ;

DROP FUNCTION IF EXISTS fn_actor;

DELIMITER $$

CREATE FUNCTION fn_actor()
RETURNS VARCHAR(50)
NOT DETERMINISTIC
READS SQL DATA
BEGIN
    RETURN IFNULL(@audit_id_usuario, 'sistema');
END$$

DELIMITER ;

CREATE TABLE IF NOT EXISTS TIPOUSUARIO (
    IDTIPOUSUARIO   VARCHAR(50)  NOT NULL PRIMARY KEY,
    DESCRIPCION     VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS USUARIO (
    IDUSUARIO           VARCHAR(50)  NOT NULL PRIMARY KEY,
    CONTRA              VARCHAR(255) NOT NULL,
    NOMBRE              VARCHAR(100) NOT NULL,
    APELLIDO            VARCHAR(100) NOT NULL,
    DNI                 VARCHAR(20)  NOT NULL UNIQUE,
    EMAIL               VARCHAR(150) NOT NULL UNIQUE,
    TELEFONO            VARCHAR(20)  NULL,
    DIRECCION           VARCHAR(255) NULL,
    ESTADO              VARCHAR(50)  NOT NULL DEFAULT 'Activo',
    FOTO                LONGTEXT NULL,
    IDTIPOUSUARIO       VARCHAR(50)  NOT NULL FOREIGN KEY REFERENCES TIPOUSUARIO(IDTIPOUSUARIO),
    CREADOPOR           VARCHAR(50)  NULL,
    FECHACREACION       CHAR(8)       NULL,
    HORACREACION        CHAR(8)       NULL,
    MODIFICADOPOR       VARCHAR(50)  NULL,
    FECHAMODIFICACION   CHAR(8)       NULL,
    HORAMODIFICACION    CHAR(8)       NULL
);

CREATE TABLE IF NOT EXISTS MODULO (
    IDMODULO            VARCHAR(50)  NOT NULL PRIMARY KEY,
    NOMBRE              VARCHAR(100) NOT NULL,
    DESCRIPCION         VARCHAR(255) NULL,
    ICONO               VARCHAR(100) NULL,
    ORDEN               INT           NULL,
    ACTIVO              TINYINT(1)           NOT NULL DEFAULT 1,
    CREADOPOR           VARCHAR(50)  NULL,
    FECHACREACION       CHAR(8)       NULL,
    HORACREACION        CHAR(8)       NULL,
    MODIFICADOPOR       VARCHAR(50)  NULL,
    FECHAMODIFICACION   CHAR(8)       NULL,
    HORAMODIFICACION    CHAR(8)       NULL
);

CREATE TABLE IF NOT EXISTS SUBMODULO (
    IDSUBMODULO     VARCHAR(50)  NOT NULL PRIMARY KEY,
    NOMBRE          VARCHAR(100) NOT NULL,
    DESCRIPCION     VARCHAR(255) NULL,
    ICONO           VARCHAR(100) NULL,
    ORDEN           INT           NULL,
    ACTIVO          TINYINT(1)           NOT NULL DEFAULT 1,
    IDMODULO        VARCHAR(50)  NOT NULL FOREIGN KEY REFERENCES MODULO(IDMODULO)
);

CREATE TABLE IF NOT EXISTS TIPO_PERMISO (
    IDTIPOPERMISO   VARCHAR(50)  NOT NULL PRIMARY KEY,
    DESCRIPCION     VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS GRUPO_MODULO (
    IDGRUPOMODULO   VARCHAR(50) NOT NULL PRIMARY KEY,
    IDTIPOUSUARIO   VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES TIPOUSUARIO(IDTIPOUSUARIO),
    IDMODULO        VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES MODULO(IDMODULO),
    IDTIPOPERMISO   VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES TIPO_PERMISO(IDTIPOPERMISO),
    CONSTRAINT UQ_GRUPO_MODULO UNIQUE (IDTIPOUSUARIO, IDMODULO, IDTIPOPERMISO)
);

CREATE TABLE IF NOT EXISTS USUARIO_MODULO (
    IDUSUARIOMODULO VARCHAR(50) NOT NULL PRIMARY KEY,
    IDUSUARIO       VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES USUARIO(IDUSUARIO),
    IDMODULO        VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES MODULO(IDMODULO),
    IDTIPOPERMISO   VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES TIPO_PERMISO(IDTIPOPERMISO),
    CONSTRAINT UQ_USUARIO_MODULO UNIQUE (IDUSUARIO, IDMODULO, IDTIPOPERMISO)
);

CREATE TABLE IF NOT EXISTS USUARIO_MODULO_EXCLUIDO (
    IDUSUARIOEXCLUIDO VARCHAR(50) NOT NULL PRIMARY KEY,
    IDUSUARIO         VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES USUARIO(IDUSUARIO),
    IDMODULO          VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES MODULO(IDMODULO),
    FECHAREGISTRO     CHAR(8) NULL,
    CONSTRAINT UQ_USUARIO_MODULO_EXCLUIDO UNIQUE (IDUSUARIO, IDMODULO)
);

CREATE TABLE IF NOT EXISTS USUARIO_SUBMODULO_EXCLUIDO (
    IDUSUARIOEXCLSUB VARCHAR(50) NOT NULL PRIMARY KEY,
    IDUSUARIO        VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES USUARIO(IDUSUARIO),
    IDSUBMODULO      VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES SUBMODULO(IDSUBMODULO),
    FECHAREGISTRO    CHAR(8) NULL,
    CONSTRAINT UQ_USUARIO_SUBMODULO_EXCLUIDO UNIQUE (IDUSUARIO, IDSUBMODULO)
);

CREATE TABLE IF NOT EXISTS GRUPO_SUBMODULO_EXCLUIDO (
    IDGRUPOEXCLSUB VARCHAR(50) NOT NULL PRIMARY KEY,
    IDTIPOUSUARIO  VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES TIPOUSUARIO(IDTIPOUSUARIO),
    IDSUBMODULO    VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES SUBMODULO(IDSUBMODULO),
    FECHAREGISTRO  CHAR(8) NULL,
    CONSTRAINT UQ_GRUPO_SUBMODULO_EXCLUIDO UNIQUE (IDTIPOUSUARIO, IDSUBMODULO)
);

CREATE TABLE IF NOT EXISTS CATEGORIA (
    IDCATEGORIA         VARCHAR(50)  NOT NULL PRIMARY KEY,
    NOMBRE              VARCHAR(150) NOT NULL,
    DESCRIPCION         VARCHAR(255) NULL,
    ORDEN               INT           NOT NULL DEFAULT 0,
    ESTADO              VARCHAR(50)  NOT NULL DEFAULT 'Activo',
    CREADOPOR           VARCHAR(50)  NULL,
    FECHACREACION       CHAR(8)       NULL,
    HORACREACION        CHAR(8)       NULL,
    MODIFICADOPOR       VARCHAR(50)  NULL,
    FECHAMODIFICACION   CHAR(8)       NULL,
    HORAMODIFICACION    CHAR(8)       NULL
);

CREATE TABLE IF NOT EXISTS UNIDAD (
    IDUNIDAD            VARCHAR(50)  NOT NULL PRIMARY KEY,
    NOMBRE              VARCHAR(100) NOT NULL,
    ABREVIATURA         VARCHAR(20)  NULL,
    ESTADO              VARCHAR(50)  NOT NULL DEFAULT 'Activo',
    CREADOPOR           VARCHAR(50)  NULL,
    FECHACREACION       CHAR(8)       NULL,
    HORACREACION        CHAR(8)       NULL,
    MODIFICADOPOR       VARCHAR(50)  NULL,
    FECHAMODIFICACION   CHAR(8)       NULL,
    HORAMODIFICACION    CHAR(8)       NULL
);

CREATE TABLE IF NOT EXISTS CLIENTE (
    IDCLIENTE           VARCHAR(50)  NOT NULL PRIMARY KEY,
    NOMBRE              VARCHAR(200) NOT NULL,
    DOCUMENTO           VARCHAR(20)  NULL,
    TELEFONO            VARCHAR(20)  NULL,
    EMAIL               VARCHAR(150) NULL,
    DIRECCION           VARCHAR(255) NULL,
    ESTADO              VARCHAR(50)  NOT NULL DEFAULT 'Activo',
    CREADOPOR           VARCHAR(50)  NULL,
    FECHACREACION       CHAR(8)       NULL,
    HORACREACION        CHAR(8)       NULL,
    MODIFICADOPOR       VARCHAR(50)  NULL,
    FECHAMODIFICACION   CHAR(8)       NULL,
    HORAMODIFICACION    CHAR(8)       NULL
);

CREATE TABLE IF NOT EXISTS FORMA_PAGO (
    IDFORMAPAGO         VARCHAR(50)  NOT NULL PRIMARY KEY,
    NOMBRE              VARCHAR(100) NOT NULL,
    ESTADO              VARCHAR(50)  NOT NULL DEFAULT 'Activo',
    CREADOPOR           VARCHAR(50)  NULL,
    FECHACREACION       CHAR(8)       NULL,
    HORACREACION        CHAR(8)       NULL,
    MODIFICADOPOR       VARCHAR(50)  NULL,
    FECHAMODIFICACION   CHAR(8)       NULL,
    HORAMODIFICACION    CHAR(8)       NULL
);

CREATE TABLE IF NOT EXISTS TIPO_ENTREGA (
    IDTIPOENTREGA       VARCHAR(50)  NOT NULL PRIMARY KEY,
    NOMBRE              VARCHAR(100) NOT NULL,
    REQUIEREDIRECCION   TINYINT(1)           NOT NULL DEFAULT 0,
    ESTADO              VARCHAR(50)  NOT NULL DEFAULT 'Activo',
    CREADOPOR           VARCHAR(50)  NULL,
    FECHACREACION       CHAR(8)       NULL,
    HORACREACION        CHAR(8)       NULL,
    MODIFICADOPOR       VARCHAR(50)  NULL,
    FECHAMODIFICACION   CHAR(8)       NULL,
    HORAMODIFICACION    CHAR(8)       NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTO (
    IDPRODUCTO          VARCHAR(50)    NOT NULL PRIMARY KEY,
    NOMBRE              VARCHAR(200)   NOT NULL,
    DESCRIPCION         LONGTEXT   NULL,
    PRECIO              DECIMAL(12,2)   NOT NULL DEFAULT 0,
    STOCK               DECIMAL(12,2)   NOT NULL DEFAULT 0,
    IDCATEGORIA         VARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES CATEGORIA(IDCATEGORIA),
    IDUNIDAD            VARCHAR(50)    NULL FOREIGN KEY REFERENCES UNIDAD(IDUNIDAD),
    ESTADO              VARCHAR(50)    NOT NULL DEFAULT 'Activo',
    FOTO                LONGTEXT   NULL,
    CREADOPOR           VARCHAR(50)    NULL,
    FECHACREACION       CHAR(8)         NULL,
    HORACREACION        CHAR(8)         NULL,
    MODIFICADOPOR       VARCHAR(50)    NULL,
    FECHAMODIFICACION   CHAR(8)         NULL,
    HORAMODIFICACION    CHAR(8)         NULL
);

CREATE TABLE IF NOT EXISTS COTIZACION (
    IDCOTIZACION        VARCHAR(50)    NOT NULL PRIMARY KEY,
    IDCLIENTE           VARCHAR(50)    NULL FOREIGN KEY REFERENCES CLIENTE(IDCLIENTE),
    NOMBRECLIENTE       VARCHAR(200)   NULL,
    IDFORMAPAGO         VARCHAR(50)    NULL FOREIGN KEY REFERENCES FORMA_PAGO(IDFORMAPAGO),
    IDTIPOENTREGA       VARCHAR(50)    NULL FOREIGN KEY REFERENCES TIPO_ENTREGA(IDTIPOENTREGA),
    DIRECCIONENTREGA    VARCHAR(255)   NULL,
    COSTODELIVERY       DECIMAL(12,2)   NOT NULL DEFAULT 0,
    SUBTOTAL            DECIMAL(12,2)   NOT NULL DEFAULT 0,
    TOTAL               DECIMAL(12,2)   NOT NULL DEFAULT 0,
    OBSERVACIONES       LONGTEXT   NULL,
    ESTADO              VARCHAR(50)    NOT NULL DEFAULT 'Deuda',
    IDVENTA             VARCHAR(50)    NULL,
    STOCKRESERVADO      TINYINT(1)             NOT NULL DEFAULT 0,
    ENVIADOPOR          VARCHAR(50)    NULL,
    FECHAENVIO          CHAR(8)         NULL,
    HORAENVIO           CHAR(8)         NULL,
    CREADOPOR           VARCHAR(50)    NULL,
    FECHACREACION       CHAR(8)         NULL,
    HORACREACION        CHAR(8)         NULL,
    MODIFICADOPOR       VARCHAR(50)    NULL,
    FECHAMODIFICACION   CHAR(8)         NULL,
    HORAMODIFICACION    CHAR(8)         NULL
);

CREATE TABLE IF NOT EXISTS COTIZACION_DETALLE (
    IDDETALLE           VARCHAR(50)    NOT NULL PRIMARY KEY,
    IDCOTIZACION        VARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES COTIZACION(IDCOTIZACION),
    IDPRODUCTO          VARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES PRODUCTO(IDPRODUCTO),
    CANTIDAD            DECIMAL(12,2)   NOT NULL,
    PRECIOUNITARIO      DECIMAL(12,2)   NOT NULL,
    SUBTOTAL            DECIMAL(12,2)   NOT NULL
);

CREATE TABLE IF NOT EXISTS COTIZACION_PAGO (
    IDPAGO              VARCHAR(50)    NOT NULL PRIMARY KEY,
    IDCOTIZACION        VARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES COTIZACION(IDCOTIZACION),
    MONTO               DECIMAL(12,2)   NOT NULL,
    TIPO                VARCHAR(50)    NOT NULL DEFAULT 'Abono',
    IDFORMAPAGO         VARCHAR(50)    NULL FOREIGN KEY REFERENCES FORMA_PAGO(IDFORMAPAGO),
    CREADOPOR           VARCHAR(50)    NULL,
    FECHACREACION       CHAR(8)         NULL,
    HORACREACION        CHAR(8)         NULL,
    MODIFICADOPOR       VARCHAR(50)    NULL,
    FECHAMODIFICACION   CHAR(8)         NULL,
    HORAMODIFICACION    CHAR(8)         NULL
);

CREATE TABLE IF NOT EXISTS VENTA (
    IDVENTA             VARCHAR(50)    NOT NULL PRIMARY KEY,
    IDCOTIZACION        VARCHAR(50)    NULL FOREIGN KEY REFERENCES COTIZACION(IDCOTIZACION),
    IDCLIENTE           VARCHAR(50)    NULL FOREIGN KEY REFERENCES CLIENTE(IDCLIENTE),
    NOMBRECLIENTE       VARCHAR(200)   NULL,
    IDFORMAPAGO         VARCHAR(50)    NULL FOREIGN KEY REFERENCES FORMA_PAGO(IDFORMAPAGO),
    IDTIPOENTREGA       VARCHAR(50)    NULL FOREIGN KEY REFERENCES TIPO_ENTREGA(IDTIPOENTREGA),
    DIRECCIONENTREGA    VARCHAR(255)   NULL,
    COSTODELIVERY       DECIMAL(12,2)   NOT NULL DEFAULT 0,
    SUBTOTAL            DECIMAL(12,2)   NOT NULL DEFAULT 0,
    TOTAL               DECIMAL(12,2)   NOT NULL DEFAULT 0,
    OBSERVACIONES       LONGTEXT   NULL,
    ESTADO              VARCHAR(50)    NOT NULL DEFAULT 'Pendiente',
    CREADOPOR           VARCHAR(50)    NULL,
    FECHACREACION       CHAR(8)         NULL,
    HORACREACION        CHAR(8)         NULL,
    MODIFICADOPOR       VARCHAR(50)    NULL,
    FECHAMODIFICACION   CHAR(8)         NULL,
    HORAMODIFICACION    CHAR(8)         NULL
);

CREATE TABLE IF NOT EXISTS VENTA_DETALLE (
    IDDETALLE           VARCHAR(50)    NOT NULL PRIMARY KEY,
    IDVENTA             VARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES VENTA(IDVENTA),
    IDPRODUCTO          VARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES PRODUCTO(IDPRODUCTO),
    CANTIDAD            DECIMAL(12,2)   NOT NULL,
    PRECIOUNITARIO      DECIMAL(12,2)   NOT NULL,
    SUBTOTAL            DECIMAL(12,2)   NOT NULL
);

CREATE TABLE IF NOT EXISTS AUDITORIA (
    IDAUDITORIA     VARCHAR(50)  NOT NULL PRIMARY KEY,
    TABLA           VARCHAR(100) NOT NULL,
    IDREGISTRO      VARCHAR(50)  NOT NULL,
    ACCION          VARCHAR(20)  NOT NULL,
    IDUSUARIO       VARCHAR(50)  NULL,
    FECHA           CHAR(8)       NOT NULL,
    HORA            CHAR(8)       NOT NULL,
    DATOS_ANTES     LONGTEXT NULL,
    DATOS_DESPUES   LONGTEXT NULL
);

CREATE INDEX IX_AUDITORIA_TABLA_FECHA ON AUDITORIA (TABLA, FECHA DESC, HORA DESC);

/* ---- Semilla ---- */
INSERT INTO TIPOUSUARIO (IDTIPOUSUARIO, DESCRIPCION) VALUES
('1', 'Vendedor'),
('2', 'Almacén'),
('3', 'Administrador');

INSERT INTO TIPO_PERMISO (IDTIPOPERMISO, DESCRIPCION) VALUES
('TP001', 'VER'),
('TP002', 'CREAR'),
('TP003', 'EDITAR'),
('TP004', 'ELIMINAR');

SET @F = fn_fecha_ddmmyyyy();
SET @H = TIME_FORMAT(NOW(), '%H:%i:%s');

INSERT INTO USUARIO (IDUSUARIO, CONTRA, NOMBRE, APELLIDO, DNI, EMAIL, TELEFONO, ESTADO, IDTIPOUSUARIO,
    CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES
('admin', '1234', 'Admin', 'Sistema', '00000001', 'admin@decocake.local', NULL, 'Activo', '3',
 'sistema', @F, @H, 'sistema', @F, @H),
('vendedor', '1234', 'Ana', 'Ventas', '00000002', 'vendedor@decocake.local', NULL, 'Activo', '1',
 'sistema', @F, @H, 'sistema', @F, @H),
('almacen', '1234', 'Luis', 'Almacén', '00000003', 'almacen@decocake.local', NULL, 'Activo', '2',
 'sistema', @F, @H, 'sistema', @F, @H);

INSERT INTO MODULO (IDMODULO, NOMBRE, DESCRIPCION, ICONO, ORDEN, ACTIVO) VALUES
('MOD001', 'Dashboard', 'Resumen de la importadora', 'faGauge', 1, 1),
('MOD002', 'Usuarios', 'Gestión de usuarios por rol', 'faUsers', 2, 1),
('MOD003', 'Productos', 'Inventario y catálogo', 'faBox', 3, 1),
('MOD004', 'Cotizaciones', 'Cotizaciones y conversión a pedido', 'faFileInvoice', 4, 1),
('MOD005', 'Pedidos', 'Pedidos confirmados con datos de envío', 'faCashRegister', 5, 1),
('MOD006', 'Mantenedores', 'Catálogos del sistema', 'faTags', 6, 1),
('MOD007', 'Auditoría', 'Historial de cambios', 'faClipboardList', 7, 1),
('MOD008', 'Administración de Módulos', 'Acceso por usuario y rol', 'faCog', 8, 1);

INSERT INTO SUBMODULO (IDSUBMODULO, IDMODULO, NOMBRE, ICONO, ORDEN, ACTIVO) VALUES
('SUB001', 'MOD006', 'Categorías', 'faLayerGroup', 1, 1),
('SUB002', 'MOD006', 'Clientes', 'faIdCard', 2, 1),
('SUB003', 'MOD006', 'Unidades', 'faBox', 3, 1),
('SUB004', 'MOD006', 'Formas de pago', 'faMoneyBill', 4, 1),
('SUB005', 'MOD006', 'Tipos de entrega', 'faTruck', 5, 1);

/* Admin: todos los módulos con todos los permisos */
INSERT INTO GRUPO_MODULO (IDGRUPOMODULO, IDTIPOUSUARIO, IDMODULO, IDTIPOPERMISO)
SELECT CONCAT('GRM3', m.IDMODULO, p.IDTIPOPERMISO), '3', m.IDMODULO, p.IDTIPOPERMISO
FROM MODULO m CROSS JOIN TIPO_PERMISO p;

/* Vendedor: dashboard, productos (ver), cotizaciones, ventas, mantenedores (clientes) */
INSERT INTO GRUPO_MODULO (IDGRUPOMODULO, IDTIPOUSUARIO, IDMODULO, IDTIPOPERMISO)
SELECT CONCAT('GRM1', x.IDMODULO, p.IDTIPOPERMISO), '1', x.IDMODULO, p.IDTIPOPERMISO
FROM (SELECT 'MOD001' AS IDMODULO UNION ALL SELECT 'MOD003' UNION ALL SELECT 'MOD004' UNION ALL SELECT 'MOD005' UNION ALL SELECT 'MOD006') x
CROSS JOIN TIPO_PERMISO p;

/* Almacén: dashboard, productos, mantenedores */
INSERT INTO GRUPO_MODULO (IDGRUPOMODULO, IDTIPOUSUARIO, IDMODULO, IDTIPOPERMISO)
SELECT CONCAT('GRM2', x.IDMODULO, p.IDTIPOPERMISO), '2', x.IDMODULO, p.IDTIPOPERMISO
FROM (SELECT 'MOD001' AS IDMODULO UNION ALL SELECT 'MOD003' UNION ALL SELECT 'MOD006') x
CROSS JOIN TIPO_PERMISO p;

INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE, DESCRIPCION, ORDEN, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES
('CAT001', 'Fondant y pastas', 'Coberturas y pastas de modelar', 1, 'Activo', 'sistema', @F, @H, 'sistema', @F, @H),
('CAT002', 'Colorantes', 'Colorantes en gel, polvo y spray', 2, 'Activo', 'sistema', @F, @H, 'sistema', @F, @H),
('CAT003', 'Moldes', 'Moldes de silicón y cortadores', 3, 'Activo', 'sistema', @F, @H, 'sistema', @F, @H);

INSERT INTO UNIDAD (IDUNIDAD, NOMBRE, ABREVIATURA, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES
('UNI001', 'Unidad', 'und', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H),
('UNI002', 'Kilogramo', 'kg', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H),
('UNI003', 'Caja', 'cja', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H);

INSERT INTO FORMA_PAGO (IDFORMAPAGO, NOMBRE, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES
('FPA001', 'Efectivo', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H),
('FPA002', 'Transferencia', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H),
('FPA003', 'Yape / Plin', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H);

INSERT INTO TIPO_ENTREGA (IDTIPOENTREGA, NOMBRE, REQUIEREDIRECCION, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES
('TEN001', 'Recojo en tienda', 0, 'Activo', 'sistema', @F, @H, 'sistema', @F, @H),
('TEN002', 'Delivery', 1, 'Activo', 'sistema', @F, @H, 'sistema', @F, @H);

INSERT INTO CLIENTE (IDCLIENTE, NOMBRE, DOCUMENTO, TELEFONO, EMAIL, DIRECCION, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES
('CLI001', 'Pastelería Dulce Luna', '20123456789', '999111222', 'luna@correo.com', 'Av. Primavera 123', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H);

INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES
('PRD001', 'Fondant blanco 1 kg', 'Pasta de cobertura', 28.50, 40, 'CAT001', 'UNI002', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H),
('PRD002', 'Colorante gel rojo', 'Gel concentrado', 12.00, 80, 'CAT002', 'UNI001', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H);

DROP PROCEDURE IF EXISTS usp_validate_user;

DELIMITER $$

CREATE PROCEDURE usp_validate_user(
    IN p_username VARCHAR(50),
    IN p_password VARCHAR(255)
)
main: BEGIN
DECLARE v_IDTIPOUSUARIO VARCHAR(50);
    SELECT IDTIPOUSUARIO INTO v_IDTIPOUSUARIO
    FROM USUARIO
    WHERE IDUSUARIO = p_username AND CONTRA = p_password AND ESTADO = 'Activo';

    IF v_IDTIPOUSUARIO IS NOT NULL THEN
        SELECT 1 AS is_valid,
            CASE v_IDTIPOUSUARIO
                WHEN '1' THEN 'vendedor'
                WHEN '2' THEN 'almacen'
                WHEN '3' THEN 'administrador'
                ELSE 'vendedor'
            END AS role;
    ELSE
        SELECT 0 AS is_valid, 'vendedor' AS role;
    END IF;
END$$

DELIMITER ;

SELECT 'Esquema DecoCake Shop creado.';

SET FOREIGN_KEY_CHECKS = 1;

