-- Convertido desde db_scripts/16_08_2026/11.modulo_pagos.sql
-- MySQL 8 — DecoCake Shop

USE `DecoCakeShop`;

/* Incremental: módulo Pagos (solo consulta de abonos recientes) */

UPDATE MODULO SET ORDEN = ORDEN + 1 WHERE ORDEN >= 6 AND NOT EXISTS (SELECT 1 FROM (SELECT IDMODULO FROM MODULO WHERE IDMODULO='MOD009') t);
INSERT INTO MODULO (IDMODULO, NOMBRE, DESCRIPCION, ICONO, ORDEN, ACTIVO)
SELECT 'MOD009', 'Pagos', 'Pagos y abonos recientes', 'faReceipt', 6, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM MODULO WHERE IDMODULO='MOD009');
UPDATE MODULO
    SET NOMBRE = 'Pagos',
        DESCRIPCION = 'Pagos y abonos recientes',
        ICONO = 'faReceipt',
        ACTIVO = 1
    WHERE IDMODULO = 'MOD009';

INSERT INTO GRUPO_MODULO (IDGRUPOMODULO, IDTIPOUSUARIO, IDMODULO, IDTIPOPERMISO)
SELECT CONCAT('GRM3MOD009', p.IDTIPOPERMISO), '3', 'MOD009', p.IDTIPOPERMISO
FROM TIPO_PERMISO p
WHERE NOT EXISTS (
    SELECT 1 FROM GRUPO_MODULO g
    WHERE g.IDTIPOUSUARIO = '3' AND g.IDMODULO = 'MOD009' AND g.IDTIPOPERMISO = p.IDTIPOPERMISO
);
INSERT INTO GRUPO_MODULO (IDGRUPOMODULO, IDTIPOUSUARIO, IDMODULO, IDTIPOPERMISO)
SELECT CONCAT('GRM1MOD009', p.IDTIPOPERMISO), '1', 'MOD009', p.IDTIPOPERMISO
FROM TIPO_PERMISO p
WHERE NOT EXISTS (
    SELECT 1 FROM GRUPO_MODULO g
    WHERE g.IDTIPOUSUARIO = '1' AND g.IDMODULO = 'MOD009' AND g.IDTIPOPERMISO = p.IDTIPOPERMISO
);

DROP PROCEDURE IF EXISTS usp_pago_listar;

DROP PROCEDURE IF EXISTS usp_pago_listar;

DELIMITER $$

CREATE PROCEDURE usp_pago_listar(
    IN p_Buscar VARCHAR(200),
    IN p_Tipo VARCHAR(50),
    IN p_OrdenarPor VARCHAR(50),
    IN p_Direccion VARCHAR(4),
    IN p_Pagina INT,
    IN p_TamanioPagina INT,
    OUT p_TotalRegistros INT
)
main: BEGIN
DECLARE v_offset INT DEFAULT 0;
    IF p_Pagina < 1 THEN SET p_Pagina = 1; END IF;
    IF p_TamanioPagina < 1 THEN SET p_TamanioPagina = 10; END IF;
    SELECT COUNT(*) INTO p_TotalRegistros
    FROM COTIZACION_PAGO p
    INNER JOIN COTIZACION q ON q.IDCOTIZACION = p.IDCOTIZACION
    LEFT JOIN CLIENTE c ON c.IDCLIENTE = q.IDCLIENTE
    LEFT JOIN FORMA_PAGO f ON f.IDFORMAPAGO = p.IDFORMAPAGO
    WHERE (p_Buscar IS NULL OR p_Buscar='' OR p.IDPAGO LIKE CONCAT('%', p_Buscar, '%')
           OR p.IDCOTIZACION LIKE CONCAT('%', p_Buscar, '%')
           OR IFNULL(c.NOMBRE, q.NOMBRECLIENTE) LIKE CONCAT('%', p_Buscar, '%')
           OR IFNULL(f.NOMBRE,'') LIKE CONCAT('%', p_Buscar, '%'))
      AND (p_Tipo IS NULL OR p_Tipo='' OR p.TIPO=p_Tipo);
    SET v_offset = (p_Pagina - 1) * p_TamanioPagina;
    SELECT p.IDPAGO, p.IDCOTIZACION, IFNULL(c.NOMBRE, q.NOMBRECLIENTE) AS CLIENTE_NOMBRE,
           p.MONTO, p.TIPO, p.IDFORMAPAGO, f.NOMBRE AS FORMAPAGO_NOMBRE,
           q.ESTADO AS COTIZACION_ESTADO, q.IDVENTA,
           p.CREADOPOR,
           CONCAT(IFNULL(NULLIF(TRIM(IFNULL(cu.NOMBRE,''), ' ', IFNULL(cu.APELLIDO,''))), ''), p.CREADOPOR) AS CREADOPOR_NOMBRE,
           p.FECHACREACION AS FECHA, p.HORACREACION AS HORA
    FROM COTIZACION_PAGO p
    INNER JOIN COTIZACION q ON q.IDCOTIZACION = p.IDCOTIZACION
    LEFT JOIN CLIENTE c ON c.IDCLIENTE = q.IDCLIENTE
    LEFT JOIN FORMA_PAGO f ON f.IDFORMAPAGO = p.IDFORMAPAGO
    LEFT JOIN USUARIO cu ON cu.IDUSUARIO = p.CREADOPOR
    WHERE (p_Buscar IS NULL OR p_Buscar='' OR p.IDPAGO LIKE CONCAT('%', p_Buscar, '%')
           OR p.IDCOTIZACION LIKE CONCAT('%', p_Buscar, '%')
           OR IFNULL(c.NOMBRE, q.NOMBRECLIENTE) LIKE CONCAT('%', p_Buscar, '%')
           OR IFNULL(f.NOMBRE,'') LIKE CONCAT('%', p_Buscar, '%'))
      AND (p_Tipo IS NULL OR p_Tipo='' OR p.TIPO=p_Tipo)
    ORDER BY
        CASE WHEN p_OrdenarPor='IDPAGO' AND p_Direccion='ASC' THEN p.IDPAGO END ASC,
        CASE WHEN p_OrdenarPor='IDPAGO' AND p_Direccion='DESC' THEN p.IDPAGO END DESC,
        CASE WHEN p_OrdenarPor='IDCOTIZACION' AND p_Direccion='ASC' THEN p.IDCOTIZACION END ASC,
        CASE WHEN p_OrdenarPor='IDCOTIZACION' AND p_Direccion='DESC' THEN p.IDCOTIZACION END DESC,
        CASE WHEN p_OrdenarPor='CLIENTE_NOMBRE' AND p_Direccion='ASC' THEN IFNULL(c.NOMBRE, q.NOMBRECLIENTE) END ASC,
        CASE WHEN p_OrdenarPor='CLIENTE_NOMBRE' AND p_Direccion='DESC' THEN IFNULL(c.NOMBRE, q.NOMBRECLIENTE) END DESC,
        CASE WHEN p_OrdenarPor='MONTO' AND p_Direccion='ASC' THEN p.MONTO END ASC,
        CASE WHEN p_OrdenarPor='MONTO' AND p_Direccion='DESC' THEN p.MONTO END DESC,
        CASE WHEN p_OrdenarPor='TIPO' AND p_Direccion='ASC' THEN p.TIPO END ASC,
        CASE WHEN p_OrdenarPor='TIPO' AND p_Direccion='DESC' THEN p.TIPO END DESC,
        CASE WHEN p_OrdenarPor='FORMAPAGO_NOMBRE' AND p_Direccion='ASC' THEN f.NOMBRE END ASC,
        CASE WHEN p_OrdenarPor='FORMAPAGO_NOMBRE' AND p_Direccion='DESC' THEN f.NOMBRE END DESC,
        CASE WHEN p_OrdenarPor='FECHA' AND p_Direccion='ASC' THEN p.FECHACREACION END ASC,
        CASE WHEN p_OrdenarPor='FECHA' AND p_Direccion='DESC' THEN p.FECHACREACION END DESC,
        CASE WHEN p_OrdenarPor='HORA' AND p_Direccion='ASC' THEN p.HORACREACION END ASC,
        CASE WHEN p_OrdenarPor='HORA' AND p_Direccion='DESC' THEN p.HORACREACION END DESC,
        p.FECHACREACION DESC, p.HORACREACION DESC, p.IDPAGO DESC
    LIMIT p_TamanioPagina OFFSET v_offset;
END$$

DELIMITER ;

DROP PROCEDURE IF EXISTS usp_pago_obtener;

DROP PROCEDURE IF EXISTS usp_pago_obtener;

DELIMITER $$

CREATE PROCEDURE usp_pago_obtener(
    IN p_Id VARCHAR(50)
)
main: BEGIN
SELECT p.IDPAGO, p.IDCOTIZACION, p.MONTO, p.TIPO, p.IDFORMAPAGO, f.NOMBRE AS FORMAPAGO_NOMBRE,
           IFNULL(c.NOMBRE, q.NOMBRECLIENTE) AS CLIENTE_NOMBRE,
           q.ESTADO AS COTIZACION_ESTADO, q.TOTAL AS COTIZACION_TOTAL, q.IDVENTA,
           IFNULL(pay.ABONADO,0) AS ABONADO, q.TOTAL - IFNULL(pay.ABONADO,0) AS SALDO,
           p.CREADOPOR,
           CONCAT(IFNULL(NULLIF(TRIM(IFNULL(cu.NOMBRE,''), ' ', IFNULL(cu.APELLIDO,''))), ''), p.CREADOPOR) AS CREADOPOR_NOMBRE,
           p.FECHACREACION AS FECHA, p.HORACREACION AS HORA,
           p.MODIFICADOPOR,
           CONCAT(IFNULL(NULLIF(TRIM(IFNULL(mu.NOMBRE,''), ' ', IFNULL(mu.APELLIDO,''))), ''), p.MODIFICADOPOR) AS MODIFICADOPOR_NOMBRE,
           p.FECHAMODIFICACION, p.HORAMODIFICACION
    FROM COTIZACION_PAGO p
    INNER JOIN COTIZACION q ON q.IDCOTIZACION = p.IDCOTIZACION
    LEFT JOIN CLIENTE c ON c.IDCLIENTE = q.IDCLIENTE
    LEFT JOIN FORMA_PAGO f ON f.IDFORMAPAGO = p.IDFORMAPAGO
    LEFT JOIN USUARIO cu ON cu.IDUSUARIO = p.CREADOPOR
    LEFT JOIN USUARIO mu ON mu.IDUSUARIO = p.MODIFICADOPOR
    LEFT JOIN (SELECT IDCOTIZACION, SUM(MONTO) AS ABONADO FROM COTIZACION_PAGO GROUP BY IDCOTIZACION) pay ON pay.IDCOTIZACION = q.IDCOTIZACION
    WHERE p.IDPAGO = p_Id;
END$$

DELIMITER ;

SELECT 'Módulo Pagos listo.';
