-- Convertido desde db_scripts/16_08_2026/14.venta_deuda.sql
-- MySQL 8 — DecoCake Shop

USE `DecoCakeShop`;

/* Incremental: saldo de cotización en listado de pedidos */

DROP PROCEDURE IF EXISTS usp_venta_listar;

DROP PROCEDURE IF EXISTS usp_venta_listar;

DELIMITER $$

CREATE PROCEDURE usp_venta_listar(
    IN p_Buscar VARCHAR(200),
    IN p_Estado VARCHAR(50),
    IN p_OrdenarPor VARCHAR(50),
    IN p_Direccion VARCHAR(4),
    IN p_Pagina INT,
    IN p_TamanioPagina INT,
    OUT p_TotalRegistros INT
)
main: BEGIN
SELECT COUNT(*) INTO p_TotalRegistros
    FROM VENTA v LEFT JOIN CLIENTE c ON c.IDCLIENTE=v.IDCLIENTE
    WHERE (p_Buscar IS NULL OR p_Buscar='' OR v.IDVENTA LIKE CONCAT('%', p_Buscar, '%') OR IFNULL(c.NOMBRE,v.NOMBRECLIENTE) LIKE CONCAT('%', p_Buscar, '%') OR IFNULL(v.IDCOTIZACION,'') LIKE CONCAT('%', p_Buscar, '%'))
      AND (p_Estado IS NULL OR p_Estado='' OR v.ESTADO=p_Estado);

    SELECT v.IDVENTA, v.IDCOTIZACION, v.IDCLIENTE, IFNULL(c.NOMBRE, v.NOMBRECLIENTE) AS CLIENTE_NOMBRE, v.NOMBRECLIENTE, v.IDFORMAPAGO, f.NOMBRE AS FORMAPAGO_NOMBRE,
           v.IDTIPOENTREGA, t.NOMBRE AS TIPOENTREGA_NOMBRE, v.DIRECCIONENTREGA, v.COSTODELIVERY, v.SUBTOTAL, v.TOTAL, v.ESTADO,
           v.FECHACREACION AS FECHA, v.HORACREACION AS HORA,
           v.CREADOPOR, TRIM(CONCAT(IFNULL(cu.NOMBRE,''), ' ', IFNULL(cu.APELLIDO,''))) AS CREADOPOR_NOMBRE,
           IFNULL(pay.ABONADO,0) AS ABONADO,
           CASE WHEN q.IDCOTIZACION IS NULL THEN CAST(0 AS DECIMAL(12,2))
                ELSE q.TOTAL - IFNULL(pay.ABONADO,0) END AS SALDO,
           CASE WHEN q.IDCOTIZACION IS NOT NULL AND (q.TOTAL - IFNULL(pay.ABONADO,0)) > 0.009 THEN 1 ELSE 0 END AS CONDEUDA
    FROM VENTA v
    LEFT JOIN CLIENTE c ON c.IDCLIENTE=v.IDCLIENTE
    LEFT JOIN FORMA_PAGO f ON f.IDFORMAPAGO=v.IDFORMAPAGO
    LEFT JOIN TIPO_ENTREGA t ON t.IDTIPOENTREGA=v.IDTIPOENTREGA
    LEFT JOIN USUARIO cu ON cu.IDUSUARIO=v.CREADOPOR
    LEFT JOIN COTIZACION q ON q.IDCOTIZACION=v.IDCOTIZACION
    LEFT JOIN (SELECT IDCOTIZACION, SUM(MONTO) AS ABONADO FROM COTIZACION_PAGO GROUP BY IDCOTIZACION) pay ON pay.IDCOTIZACION = v.IDCOTIZACION
    WHERE (p_Buscar IS NULL OR p_Buscar='' OR v.IDVENTA LIKE CONCAT('%', p_Buscar, '%') OR IFNULL(c.NOMBRE,v.NOMBRECLIENTE) LIKE CONCAT('%', p_Buscar, '%') OR IFNULL(v.IDCOTIZACION,'') LIKE CONCAT('%', p_Buscar, '%'))
      AND (p_Estado IS NULL OR p_Estado='' OR v.ESTADO=p_Estado)
    ORDER BY v.FECHACREACION DESC, v.HORACREACION DESC, v.IDVENTA DESC
    LIMIT p_TamanioPagina OFFSET ((p_Pagina - 1) * p_TamanioPagina);
END$$

DELIMITER ;

DROP PROCEDURE IF EXISTS usp_venta_obtener;

DROP PROCEDURE IF EXISTS usp_venta_obtener;

DELIMITER $$

CREATE PROCEDURE usp_venta_obtener(
    IN p_Id VARCHAR(50)
)
main: BEGIN
SELECT v.*, IFNULL(c.NOMBRE, v.NOMBRECLIENTE) AS CLIENTE_NOMBRE, f.NOMBRE AS FORMAPAGO_NOMBRE, t.NOMBRE AS TIPOENTREGA_NOMBRE,
           v.FECHACREACION AS FECHA, v.HORACREACION AS HORA,
           IFNULL(pay.ABONADO,0) AS ABONADO,
           CASE WHEN q.IDCOTIZACION IS NULL THEN CAST(0 AS DECIMAL(12,2))
                ELSE q.TOTAL - IFNULL(pay.ABONADO,0) END AS SALDO,
           CASE WHEN q.IDCOTIZACION IS NOT NULL AND (q.TOTAL - IFNULL(pay.ABONADO,0)) > 0.009 THEN 1 ELSE 0 END AS CONDEUDA
    FROM VENTA v
    LEFT JOIN CLIENTE c ON c.IDCLIENTE=v.IDCLIENTE
    LEFT JOIN FORMA_PAGO f ON f.IDFORMAPAGO=v.IDFORMAPAGO
    LEFT JOIN TIPO_ENTREGA t ON t.IDTIPOENTREGA=v.IDTIPOENTREGA
    LEFT JOIN COTIZACION q ON q.IDCOTIZACION=v.IDCOTIZACION
    LEFT JOIN (SELECT IDCOTIZACION, SUM(MONTO) AS ABONADO FROM COTIZACION_PAGO GROUP BY IDCOTIZACION) pay ON pay.IDCOTIZACION = v.IDCOTIZACION
    WHERE v.IDVENTA=p_Id;
END$$

DELIMITER ;

SELECT 'Pedidos con saldo de cotización listos.';
