-- Convertido desde db_scripts/16_08_2026/16.productos_catalogo.sql
-- MySQL 8 — DecoCake Shop

USE `DecoCakeShop`;

/* Productos extra para el catálogo público */

INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
SELECT 'PRD003', 'Colorante gel rosa', 'Gel concentrado tono rosa pastel', 12.00, 70, 'CAT002', 'UNI001', 'Activo', 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s'), 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE IDPRODUCTO = 'PRD003') AND NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE = 'Colorante gel rosa');
INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
SELECT 'PRD004', 'Colorante gel amarillo', 'Gel concentrado para masas y cremas', 12.00, 65, 'CAT002', 'UNI001', 'Activo', 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s'), 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE IDPRODUCTO = 'PRD004') AND NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE = 'Colorante gel amarillo');
INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
SELECT 'PRD005', 'Fondant negro 1 kg', 'Pasta de cobertura color intenso', 29.50, 35, 'CAT001', 'UNI002', 'Activo', 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s'), 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE IDPRODUCTO = 'PRD005') AND NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE = 'Fondant negro 1 kg');
INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
SELECT 'PRD006', 'Pasta de goma 500 g', 'Para modelado de figuras y flores', 18.00, 40, 'CAT001', 'UNI001', 'Activo', 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s'), 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE IDPRODUCTO = 'PRD006') AND NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE = 'Pasta de goma 500 g');
INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
SELECT 'PRD007', 'Molde silicona cupcake', '12 cavidades, antiadherente', 22.00, 28, 'CAT003', 'UNI001', 'Activo', 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s'), 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE IDPRODUCTO = 'PRD007') AND NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE = 'Molde silicona cupcake');
INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
SELECT 'PRD008', 'Cortador flor set', 'Set de 6 cortadores para fondant', 15.50, 45, 'CAT003', 'UNI001', 'Activo', 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s'), 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE IDPRODUCTO = 'PRD008') AND NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE = 'Cortador flor set');
INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
SELECT 'PRD009', 'Molde número 3D', 'Molde para tortas numéricas', 19.90, 22, 'CAT003', 'UNI001', 'Activo', 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s'), 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE IDPRODUCTO = 'PRD009') AND NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE = 'Molde número 3D');
INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
SELECT 'PRD010', 'Sprinkles perlados 100 g', 'Perlas comestibles para decoración', 8.50, 90, 'CAT001', 'UNI001', 'Activo', 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s'), 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE IDPRODUCTO = 'PRD010') AND NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE = 'Sprinkles perlados 100 g');

SELECT 'Productos de catálogo listos.';
