-- Convertido desde db_scripts/16_08_2026/18.productos_tienda.sql
-- MySQL 8 — DecoCake Shop

USE `DecoCakeShop`;

/* Productos e imágenes de la tienda pública */

INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE, DESCRIPCION, ORDEN, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
SELECT 'CAT004', 'Utensilios', 'Rodillos, balanzas y accesorios de trabajo', 4, 'Activo', 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s'), 'sistema', fn_fecha_ddmmyyyy(), TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE IDCATEGORIA='CAT004');

UPDATE PRODUCTO SET FOTO='/shop-products/04-taper-bombonera.png' WHERE IDPRODUCTO='PRD001' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO='/shop-products/03-sorbetones.png' WHERE IDPRODUCTO='PRD002' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO='/shop-products/03-sorbetones.png' WHERE IDPRODUCTO='PRD003' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO='/shop-products/03-sorbetones.png' WHERE IDPRODUCTO='PRD004' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO='/shop-products/04-taper-bombonera.png' WHERE IDPRODUCTO='PRD005' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO='/shop-products/02-estatulas-x3-und.jpeg' WHERE IDPRODUCTO='PRD006' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO='/shop-products/12-kekera-rectangular-x5-und.jpeg' WHERE IDPRODUCTO='PRD007' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO='/shop-products/01-cortador-y-alisador.png' WHERE IDPRODUCTO='PRD008' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO='/shop-products/17-molde-keke-ingles-x3-und.jpeg' WHERE IDPRODUCTO='PRD009' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO='/shop-products/03-sorbetones.png' WHERE IDPRODUCTO='PRD010' AND (FOTO IS NULL OR FOTO='');

INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD011','Cortador y alisador','Cortador y alisador para fondant',12.00,40,'CAT003','UNI001','Activo','/shop-products/01-cortador-y-alisador.png','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Cortador y alisador');
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD012','Espátulas x3 und','Espátulas por 3 unidades',8.00,50,'CAT004','UNI001','Activo','/shop-products/02-estatulas-x3-und.jpeg','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Espátulas x3 und');
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD013','Sorbetones x50 und','Sorbetones por 50 unidades',7.00,80,'CAT004','UNI001','Activo','/shop-products/03-sorbetones.png','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Sorbetones x50 und');
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD014','Taper bombonera','Tapa alta. Material PET. Medida: 8 onz.',35.00,25,'CAT004','UNI001','Activo','/shop-products/04-taper-bombonera.png','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Taper bombonera');
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD015','Bowls de acero x7 und','Set de 7 bowls metálicos. Medidas 18/20/22/24/26/28/30 cm.',58.00,18,'CAT004','UNI001','Activo','/shop-products/05-bols-de-acero-x7und.png','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Bowls de acero x7 und');
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD016','Rodillo de acero 40 cm','Rodillo de acero con medidas',18.00,30,'CAT004','UNI001','Activo','/shop-products/06-rodillo-de-acero-40-cm.png','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Rodillo de acero 40 cm');
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD017','Rodillo acrílico 23 cm','Rodillo acrílico de 23 cm',8.00,35,'CAT004','UNI001','Activo','/shop-products/07-rodillo-acrilico-23-cm.png','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Rodillo acrílico 23 cm');
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD018','Rodillo acrílico 40 cm','Rodillo acrílico 40 cm',15.00,28,'CAT004','UNI001','Activo','/shop-products/08-rodillo-acrilico-40-cm.png','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Rodillo acrílico 40 cm');
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD019','Rodillo acrílico 50 cm','Rodillo acrílico 50 cm',19.00,22,'CAT004','UNI001','Activo','/shop-products/09-rodillo-en-acrilico-50-cm.png','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Rodillo acrílico 50 cm');
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD020','Mini gramera','Mini gramera de precisión',15.00,40,'CAT004','UNI001','Activo','/shop-products/10-mini-gramera.png','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Mini gramera');
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD021','Balanza clásica','Balanza clásica hasta 5 kg. Color rosada.',12.00,26,'CAT004','UNI001','Activo','/shop-products/11-balanza-clasica.png','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Balanza clásica');
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD022','Kekera rectangular x5 und','Set de 5 kekeras rectangulares',32.00,16,'CAT003','UNI001','Activo','/shop-products/12-kekera-rectangular-x5-und.jpeg','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Kekera rectangular x5 und');
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD023','Balanza de corazón','Balanza de corazón hasta 5 kg',25.00,20,'CAT004','UNI001','Activo','/shop-products/13-balanza-de-corazon.png','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Balanza de corazón');
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD024','Balanza de vidrio','Balanza de vidrio hasta 5 kg',20.00,18,'CAT004','UNI001','Activo','/shop-products/14-balanza-de-vidrio.png','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Balanza de vidrio');
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD025','Kekera corazón x5 und','Set de 5 kekeras en forma de corazón',32.00,14,'CAT003','UNI001','Activo','/shop-products/15-kekera-coraz-n-x5-und.jpeg','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Kekera corazón x5 und');
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD026','Kekeras cuadradas x5 und','Medidas 15, 20, 25, 30 y 35 cm',32.00,14,'CAT003','UNI001','Activo','/shop-products/16-kekeras-cuadradas-x5-und.jpeg','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Kekeras cuadradas x5 und');
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD027','Molde keke inglés x3 und','Medidas 22x11, 28x11 y 32x11 cm',14.00,20,'CAT003','UNI001','Activo','/shop-products/17-molde-keke-ingles-x3-und.jpeg','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Molde keke inglés x3 und');
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
SELECT 'PRD028','Terrinas x3 unidades','15, 18 y 25 tajadas',26.00,16,'CAT003','UNI001','Activo','/shop-products/18-terrinas-x3-unidades.jpeg','sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s'),'sistema',fn_fecha_ddmmyyyy(),TIME_FORMAT(NOW(), '%H:%i:%s') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE='Terrinas x3 unidades');

SELECT 'Productos de tienda con fotos listos.';
