-- Convertido desde db_scripts/16_08_2026/4.cotizacion_amigable.sql
-- MySQL 8 — DecoCake Shop

USE `DecoCakeShop`;

/* Incremental: foto Base64 en producto + cliente libre en cotización/venta */

ALTER TABLE PRODUCTO ADD COLUMN FOTO LONGTEXT NULL;

ALTER TABLE COTIZACION ADD COLUMN NOMBRECLIENTE VARCHAR(200) NULL;

ALTER TABLE VENTA ADD COLUMN NOMBRECLIENTE VARCHAR(200) NULL;

-- SQL Server sys.foreign_keys skip (esquema MySQL ya tiene IDCLIENTE NULL)

ALTER TABLE COTIZACION MODIFY IDCLIENTE VARCHAR(50) NULL;
ALTER TABLE VENTA MODIFY IDCLIENTE VARCHAR(50) NULL;

-- FK FK_COTIZACION_CLIENTE already in schema or ignored (1826)
ALTER TABLE COTIZACION ADD CONSTRAINT FK_COTIZACION_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);
-- FK FK_VENTA_CLIENTE already in schema or ignored (1826)
ALTER TABLE VENTA ADD CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);

UPDATE COTIZACION q INNER JOIN CLIENTE c ON c.IDCLIENTE = q.IDCLIENTE SET q.NOMBRECLIENTE = c.NOMBRE WHERE q.NOMBRECLIENTE IS NULL;
UPDATE VENTA v INNER JOIN CLIENTE c ON c.IDCLIENTE = v.IDCLIENTE SET v.NOMBRECLIENTE = c.NOMBRE WHERE v.NOMBRECLIENTE IS NULL;

UPDATE COTIZACION SET ESTADO = 'Cotizado' WHERE ESTADO IN ('Borrador');
UPDATE COTIZACION SET ESTADO = 'Enviado' WHERE ESTADO IN ('Enviada');
UPDATE COTIZACION SET ESTADO = 'Aceptado' WHERE ESTADO IN ('Aceptada');

SELECT 'Columnas foto y cliente libre listas.';
