/* ============================================================================
   DECOCAKE SHOP — Importadora
   Esquema completo SQL Server (destructivo: recrea la BD de negocio)
   Fecha: 16/08/2026
   Convenciones (igual Academia 3.0):
     - Tablas/columnas MAYÚSCULAS
     - IDs NVARCHAR(50) con prefijo
     - FECHA CHAR(8) DDMMYYYY | HORA CHAR(8) HH:MM:SS
     - Auditoría en tablas principales: CREADOPOR, FECHACREACION, HORACREACION,
       MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION
   ============================================================================ */

IF OBJECT_ID('dbo.usp_validate_user', 'P') IS NOT NULL DROP PROCEDURE dbo.usp_validate_user;
IF OBJECT_ID('dbo.fn_fecha_ddmmyyyy', 'FN') IS NOT NULL DROP FUNCTION dbo.fn_fecha_ddmmyyyy;
IF OBJECT_ID('dbo.fn_actor', 'FN') IS NOT NULL DROP FUNCTION dbo.fn_actor;
GO

DROP TABLE IF EXISTS COTIZACION_PAGO;
DROP TABLE IF EXISTS COTIZACION_DETALLE;
DROP TABLE IF EXISTS VENTA_DETALLE;
DROP TABLE IF EXISTS VENTA;
DROP TABLE IF EXISTS COTIZACION;
DROP TABLE IF EXISTS PRODUCTO;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS UNIDAD;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS FORMA_PAGO;
DROP TABLE IF EXISTS TIPO_ENTREGA;
DROP TABLE IF EXISTS AUDITORIA;
DROP TABLE IF EXISTS USUARIO_SUBMODULO_EXCLUIDO;
DROP TABLE IF EXISTS GRUPO_SUBMODULO_EXCLUIDO;
DROP TABLE IF EXISTS USUARIO_MODULO_EXCLUIDO;
DROP TABLE IF EXISTS USUARIO_MODULO;
DROP TABLE IF EXISTS GRUPO_MODULO;
DROP TABLE IF EXISTS TIPO_PERMISO;
DROP TABLE IF EXISTS SUBMODULO;
DROP TABLE IF EXISTS MODULO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS TIPOUSUARIO;
GO

CREATE FUNCTION dbo.fn_fecha_ddmmyyyy()
RETURNS CHAR(8)
AS
BEGIN
    RETURN (
        RIGHT('0' + CAST(DAY(GETDATE()) AS VARCHAR(2)), 2) +
        RIGHT('0' + CAST(MONTH(GETDATE()) AS VARCHAR(2)), 2) +
        CAST(YEAR(GETDATE()) AS VARCHAR(4))
    );
END;
GO

CREATE FUNCTION dbo.fn_actor()
RETURNS NVARCHAR(50)
AS
BEGIN
    RETURN ISNULL(TRY_CAST(SESSION_CONTEXT(N'IDUSUARIO') AS NVARCHAR(50)), N'sistema');
END;
GO

CREATE TABLE TIPOUSUARIO (
    IDTIPOUSUARIO   NVARCHAR(50)  NOT NULL PRIMARY KEY,
    DESCRIPCION     NVARCHAR(255) NOT NULL
);
GO

CREATE TABLE USUARIO (
    IDUSUARIO           NVARCHAR(50)  NOT NULL PRIMARY KEY,
    CONTRA              NVARCHAR(255) NOT NULL,
    NOMBRE              NVARCHAR(100) NOT NULL,
    APELLIDO            NVARCHAR(100) NOT NULL,
    DNI                 NVARCHAR(20)  NOT NULL UNIQUE,
    EMAIL               NVARCHAR(150) NOT NULL UNIQUE,
    TELEFONO            NVARCHAR(20)  NULL,
    DIRECCION           NVARCHAR(255) NULL,
    ESTADO              NVARCHAR(50)  NOT NULL DEFAULT 'Activo',
    FOTO                NVARCHAR(MAX) NULL,
    IDTIPOUSUARIO       NVARCHAR(50)  NOT NULL FOREIGN KEY REFERENCES TIPOUSUARIO(IDTIPOUSUARIO),
    CREADOPOR           NVARCHAR(50)  NULL,
    FECHACREACION       CHAR(8)       NULL,
    HORACREACION        CHAR(8)       NULL,
    MODIFICADOPOR       NVARCHAR(50)  NULL,
    FECHAMODIFICACION   CHAR(8)       NULL,
    HORAMODIFICACION    CHAR(8)       NULL
);
GO

CREATE TABLE MODULO (
    IDMODULO            NVARCHAR(50)  NOT NULL PRIMARY KEY,
    NOMBRE              NVARCHAR(100) NOT NULL,
    DESCRIPCION         NVARCHAR(255) NULL,
    ICONO               NVARCHAR(100) NULL,
    ORDEN               INT           NULL,
    ACTIVO              BIT           NOT NULL DEFAULT 1,
    CREADOPOR           NVARCHAR(50)  NULL,
    FECHACREACION       CHAR(8)       NULL,
    HORACREACION        CHAR(8)       NULL,
    MODIFICADOPOR       NVARCHAR(50)  NULL,
    FECHAMODIFICACION   CHAR(8)       NULL,
    HORAMODIFICACION    CHAR(8)       NULL
);
GO

CREATE TABLE SUBMODULO (
    IDSUBMODULO     NVARCHAR(50)  NOT NULL PRIMARY KEY,
    NOMBRE          NVARCHAR(100) NOT NULL,
    DESCRIPCION     NVARCHAR(255) NULL,
    ICONO           NVARCHAR(100) NULL,
    ORDEN           INT           NULL,
    ACTIVO          BIT           NOT NULL DEFAULT 1,
    IDMODULO        NVARCHAR(50)  NOT NULL FOREIGN KEY REFERENCES MODULO(IDMODULO)
);
GO

CREATE TABLE TIPO_PERMISO (
    IDTIPOPERMISO   NVARCHAR(50)  NOT NULL PRIMARY KEY,
    DESCRIPCION     NVARCHAR(255) NOT NULL
);
GO

CREATE TABLE GRUPO_MODULO (
    IDGRUPOMODULO   NVARCHAR(50) NOT NULL PRIMARY KEY,
    IDTIPOUSUARIO   NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES TIPOUSUARIO(IDTIPOUSUARIO),
    IDMODULO        NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES MODULO(IDMODULO),
    IDTIPOPERMISO   NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES TIPO_PERMISO(IDTIPOPERMISO),
    CONSTRAINT UQ_GRUPO_MODULO UNIQUE (IDTIPOUSUARIO, IDMODULO, IDTIPOPERMISO)
);
GO

CREATE TABLE USUARIO_MODULO (
    IDUSUARIOMODULO NVARCHAR(50) NOT NULL PRIMARY KEY,
    IDUSUARIO       NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES USUARIO(IDUSUARIO),
    IDMODULO        NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES MODULO(IDMODULO),
    IDTIPOPERMISO   NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES TIPO_PERMISO(IDTIPOPERMISO),
    CONSTRAINT UQ_USUARIO_MODULO UNIQUE (IDUSUARIO, IDMODULO, IDTIPOPERMISO)
);
GO

CREATE TABLE USUARIO_MODULO_EXCLUIDO (
    IDUSUARIOEXCLUIDO NVARCHAR(50) NOT NULL PRIMARY KEY,
    IDUSUARIO         NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES USUARIO(IDUSUARIO),
    IDMODULO          NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES MODULO(IDMODULO),
    FECHAREGISTRO     CHAR(8) NULL,
    CONSTRAINT UQ_USUARIO_MODULO_EXCLUIDO UNIQUE (IDUSUARIO, IDMODULO)
);
GO

CREATE TABLE USUARIO_SUBMODULO_EXCLUIDO (
    IDUSUARIOEXCLSUB NVARCHAR(50) NOT NULL PRIMARY KEY,
    IDUSUARIO        NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES USUARIO(IDUSUARIO),
    IDSUBMODULO      NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES SUBMODULO(IDSUBMODULO),
    FECHAREGISTRO    CHAR(8) NULL,
    CONSTRAINT UQ_USUARIO_SUBMODULO_EXCLUIDO UNIQUE (IDUSUARIO, IDSUBMODULO)
);
GO

CREATE TABLE GRUPO_SUBMODULO_EXCLUIDO (
    IDGRUPOEXCLSUB NVARCHAR(50) NOT NULL PRIMARY KEY,
    IDTIPOUSUARIO  NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES TIPOUSUARIO(IDTIPOUSUARIO),
    IDSUBMODULO    NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES SUBMODULO(IDSUBMODULO),
    FECHAREGISTRO  CHAR(8) NULL,
    CONSTRAINT UQ_GRUPO_SUBMODULO_EXCLUIDO UNIQUE (IDTIPOUSUARIO, IDSUBMODULO)
);
GO

CREATE TABLE CATEGORIA (
    IDCATEGORIA         NVARCHAR(50)  NOT NULL PRIMARY KEY,
    NOMBRE              NVARCHAR(150) NOT NULL,
    DESCRIPCION         NVARCHAR(255) NULL,
    ORDEN               INT           NOT NULL DEFAULT 0,
    ESTADO              NVARCHAR(50)  NOT NULL DEFAULT 'Activo',
    CREADOPOR           NVARCHAR(50)  NULL,
    FECHACREACION       CHAR(8)       NULL,
    HORACREACION        CHAR(8)       NULL,
    MODIFICADOPOR       NVARCHAR(50)  NULL,
    FECHAMODIFICACION   CHAR(8)       NULL,
    HORAMODIFICACION    CHAR(8)       NULL
);
GO

CREATE TABLE UNIDAD (
    IDUNIDAD            NVARCHAR(50)  NOT NULL PRIMARY KEY,
    NOMBRE              NVARCHAR(100) NOT NULL,
    ABREVIATURA         NVARCHAR(20)  NULL,
    ESTADO              NVARCHAR(50)  NOT NULL DEFAULT 'Activo',
    CREADOPOR           NVARCHAR(50)  NULL,
    FECHACREACION       CHAR(8)       NULL,
    HORACREACION        CHAR(8)       NULL,
    MODIFICADOPOR       NVARCHAR(50)  NULL,
    FECHAMODIFICACION   CHAR(8)       NULL,
    HORAMODIFICACION    CHAR(8)       NULL
);
GO

CREATE TABLE CLIENTE (
    IDCLIENTE           NVARCHAR(50)  NOT NULL PRIMARY KEY,
    NOMBRE              NVARCHAR(200) NOT NULL,
    DOCUMENTO           NVARCHAR(20)  NULL,
    TELEFONO            NVARCHAR(20)  NULL,
    EMAIL               NVARCHAR(150) NULL,
    DIRECCION           NVARCHAR(255) NULL,
    ESTADO              NVARCHAR(50)  NOT NULL DEFAULT 'Activo',
    CREADOPOR           NVARCHAR(50)  NULL,
    FECHACREACION       CHAR(8)       NULL,
    HORACREACION        CHAR(8)       NULL,
    MODIFICADOPOR       NVARCHAR(50)  NULL,
    FECHAMODIFICACION   CHAR(8)       NULL,
    HORAMODIFICACION    CHAR(8)       NULL
);
GO

CREATE TABLE FORMA_PAGO (
    IDFORMAPAGO         NVARCHAR(50)  NOT NULL PRIMARY KEY,
    NOMBRE              NVARCHAR(100) NOT NULL,
    ESTADO              NVARCHAR(50)  NOT NULL DEFAULT 'Activo',
    CREADOPOR           NVARCHAR(50)  NULL,
    FECHACREACION       CHAR(8)       NULL,
    HORACREACION        CHAR(8)       NULL,
    MODIFICADOPOR       NVARCHAR(50)  NULL,
    FECHAMODIFICACION   CHAR(8)       NULL,
    HORAMODIFICACION    CHAR(8)       NULL
);
GO

CREATE TABLE TIPO_ENTREGA (
    IDTIPOENTREGA       NVARCHAR(50)  NOT NULL PRIMARY KEY,
    NOMBRE              NVARCHAR(100) NOT NULL,
    REQUIEREDIRECCION   BIT           NOT NULL DEFAULT 0,
    ESTADO              NVARCHAR(50)  NOT NULL DEFAULT 'Activo',
    CREADOPOR           NVARCHAR(50)  NULL,
    FECHACREACION       CHAR(8)       NULL,
    HORACREACION        CHAR(8)       NULL,
    MODIFICADOPOR       NVARCHAR(50)  NULL,
    FECHAMODIFICACION   CHAR(8)       NULL,
    HORAMODIFICACION    CHAR(8)       NULL
);
GO

CREATE TABLE PRODUCTO (
    IDPRODUCTO          NVARCHAR(50)    NOT NULL PRIMARY KEY,
    NOMBRE              NVARCHAR(200)   NOT NULL,
    DESCRIPCION         NVARCHAR(MAX)   NULL,
    PRECIO              DECIMAL(12,2)   NOT NULL DEFAULT 0,
    STOCK               DECIMAL(12,2)   NOT NULL DEFAULT 0,
    IDCATEGORIA         NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES CATEGORIA(IDCATEGORIA),
    IDUNIDAD            NVARCHAR(50)    NULL FOREIGN KEY REFERENCES UNIDAD(IDUNIDAD),
    ESTADO              NVARCHAR(50)    NOT NULL DEFAULT 'Activo',
    FOTO                NVARCHAR(MAX)   NULL,
    CREADOPOR           NVARCHAR(50)    NULL,
    FECHACREACION       CHAR(8)         NULL,
    HORACREACION        CHAR(8)         NULL,
    MODIFICADOPOR       NVARCHAR(50)    NULL,
    FECHAMODIFICACION   CHAR(8)         NULL,
    HORAMODIFICACION    CHAR(8)         NULL
);
GO

CREATE TABLE COTIZACION (
    IDCOTIZACION        NVARCHAR(50)    NOT NULL PRIMARY KEY,
    IDCLIENTE           NVARCHAR(50)    NULL FOREIGN KEY REFERENCES CLIENTE(IDCLIENTE),
    NOMBRECLIENTE       NVARCHAR(200)   NULL,
    IDFORMAPAGO         NVARCHAR(50)    NULL FOREIGN KEY REFERENCES FORMA_PAGO(IDFORMAPAGO),
    IDTIPOENTREGA       NVARCHAR(50)    NULL FOREIGN KEY REFERENCES TIPO_ENTREGA(IDTIPOENTREGA),
    DIRECCIONENTREGA    NVARCHAR(255)   NULL,
    COSTODELIVERY       DECIMAL(12,2)   NOT NULL DEFAULT 0,
    SUBTOTAL            DECIMAL(12,2)   NOT NULL DEFAULT 0,
    TOTAL               DECIMAL(12,2)   NOT NULL DEFAULT 0,
    OBSERVACIONES       NVARCHAR(MAX)   NULL,
    ESTADO              NVARCHAR(50)    NOT NULL DEFAULT 'Deuda',
    IDVENTA             NVARCHAR(50)    NULL,
    STOCKRESERVADO      BIT             NOT NULL DEFAULT 0,
    ENVIADOPOR          NVARCHAR(50)    NULL,
    FECHAENVIO          CHAR(8)         NULL,
    HORAENVIO           CHAR(8)         NULL,
    CREADOPOR           NVARCHAR(50)    NULL,
    FECHACREACION       CHAR(8)         NULL,
    HORACREACION        CHAR(8)         NULL,
    MODIFICADOPOR       NVARCHAR(50)    NULL,
    FECHAMODIFICACION   CHAR(8)         NULL,
    HORAMODIFICACION    CHAR(8)         NULL
);
GO

CREATE TABLE COTIZACION_DETALLE (
    IDDETALLE           NVARCHAR(50)    NOT NULL PRIMARY KEY,
    IDCOTIZACION        NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES COTIZACION(IDCOTIZACION),
    IDPRODUCTO          NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES PRODUCTO(IDPRODUCTO),
    CANTIDAD            DECIMAL(12,2)   NOT NULL,
    PRECIOUNITARIO      DECIMAL(12,2)   NOT NULL,
    SUBTOTAL            DECIMAL(12,2)   NOT NULL
);
GO

CREATE TABLE COTIZACION_PAGO (
    IDPAGO              NVARCHAR(50)    NOT NULL PRIMARY KEY,
    IDCOTIZACION        NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES COTIZACION(IDCOTIZACION),
    MONTO               DECIMAL(12,2)   NOT NULL,
    TIPO                NVARCHAR(50)    NOT NULL DEFAULT 'Abono',
    IDFORMAPAGO         NVARCHAR(50)    NULL FOREIGN KEY REFERENCES FORMA_PAGO(IDFORMAPAGO),
    CREADOPOR           NVARCHAR(50)    NULL,
    FECHACREACION       CHAR(8)         NULL,
    HORACREACION        CHAR(8)         NULL,
    MODIFICADOPOR       NVARCHAR(50)    NULL,
    FECHAMODIFICACION   CHAR(8)         NULL,
    HORAMODIFICACION    CHAR(8)         NULL
);
GO

CREATE TABLE VENTA (
    IDVENTA             NVARCHAR(50)    NOT NULL PRIMARY KEY,
    IDCOTIZACION        NVARCHAR(50)    NULL FOREIGN KEY REFERENCES COTIZACION(IDCOTIZACION),
    IDCLIENTE           NVARCHAR(50)    NULL FOREIGN KEY REFERENCES CLIENTE(IDCLIENTE),
    NOMBRECLIENTE       NVARCHAR(200)   NULL,
    IDFORMAPAGO         NVARCHAR(50)    NULL FOREIGN KEY REFERENCES FORMA_PAGO(IDFORMAPAGO),
    IDTIPOENTREGA       NVARCHAR(50)    NULL FOREIGN KEY REFERENCES TIPO_ENTREGA(IDTIPOENTREGA),
    DIRECCIONENTREGA    NVARCHAR(255)   NULL,
    COSTODELIVERY       DECIMAL(12,2)   NOT NULL DEFAULT 0,
    SUBTOTAL            DECIMAL(12,2)   NOT NULL DEFAULT 0,
    TOTAL               DECIMAL(12,2)   NOT NULL DEFAULT 0,
    OBSERVACIONES       NVARCHAR(MAX)   NULL,
    ESTADO              NVARCHAR(50)    NOT NULL DEFAULT 'Pendiente',
    CREADOPOR           NVARCHAR(50)    NULL,
    FECHACREACION       CHAR(8)         NULL,
    HORACREACION        CHAR(8)         NULL,
    MODIFICADOPOR       NVARCHAR(50)    NULL,
    FECHAMODIFICACION   CHAR(8)         NULL,
    HORAMODIFICACION    CHAR(8)         NULL
);
GO

CREATE TABLE VENTA_DETALLE (
    IDDETALLE           NVARCHAR(50)    NOT NULL PRIMARY KEY,
    IDVENTA             NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES VENTA(IDVENTA),
    IDPRODUCTO          NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES PRODUCTO(IDPRODUCTO),
    CANTIDAD            DECIMAL(12,2)   NOT NULL,
    PRECIOUNITARIO      DECIMAL(12,2)   NOT NULL,
    SUBTOTAL            DECIMAL(12,2)   NOT NULL
);
GO

CREATE TABLE AUDITORIA (
    IDAUDITORIA     NVARCHAR(50)  NOT NULL PRIMARY KEY,
    TABLA           NVARCHAR(100) NOT NULL,
    IDREGISTRO      NVARCHAR(50)  NOT NULL,
    ACCION          NVARCHAR(20)  NOT NULL,
    IDUSUARIO       NVARCHAR(50)  NULL,
    FECHA           CHAR(8)       NOT NULL,
    HORA            CHAR(8)       NOT NULL,
    DATOS_ANTES     NVARCHAR(MAX) NULL,
    DATOS_DESPUES   NVARCHAR(MAX) NULL
);
GO
CREATE INDEX IX_AUDITORIA_TABLA_FECHA ON AUDITORIA (TABLA, FECHA DESC, HORA DESC);
GO

/* ---- Semilla ---- */
INSERT INTO TIPOUSUARIO (IDTIPOUSUARIO, DESCRIPCION) VALUES
('1', 'Vendedor'),
('2', 'Almacén'),
('3', 'Administrador');

INSERT INTO TIPO_PERMISO (IDTIPOPERMISO, DESCRIPCION) VALUES
('TP001', 'VER'),
('TP002', 'CREAR'),
('TP003', 'EDITAR'),
('TP004', 'ELIMINAR');

DECLARE @F CHAR(8) = dbo.fn_fecha_ddmmyyyy();
DECLARE @H CHAR(8) = CONVERT(CHAR(8), GETDATE(), 108);

INSERT INTO USUARIO (IDUSUARIO, CONTRA, NOMBRE, APELLIDO, DNI, EMAIL, TELEFONO, ESTADO, IDTIPOUSUARIO,
    CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES
('admin', '1234', 'Admin', 'Sistema', '00000001', 'admin@decocake.local', NULL, 'Activo', '3',
 'sistema', @F, @H, 'sistema', @F, @H),
('vendedor', '1234', 'Ana', 'Ventas', '00000002', 'vendedor@decocake.local', NULL, 'Activo', '1',
 'sistema', @F, @H, 'sistema', @F, @H),
('almacen', '1234', 'Luis', 'Almacén', '00000003', 'almacen@decocake.local', NULL, 'Activo', '2',
 'sistema', @F, @H, 'sistema', @F, @H);

INSERT INTO MODULO (IDMODULO, NOMBRE, DESCRIPCION, ICONO, ORDEN, ACTIVO) VALUES
('MOD001', 'Dashboard', 'Resumen de la importadora', 'faGauge', 1, 1),
('MOD002', 'Usuarios', 'Gestión de usuarios por rol', 'faUsers', 2, 1),
('MOD003', 'Productos', 'Inventario y catálogo', 'faBox', 3, 1),
('MOD004', 'Cotizaciones', 'Cotizaciones y conversión a pedido', 'faFileInvoice', 4, 1),
('MOD005', 'Pedidos', 'Pedidos confirmados con datos de envío', 'faCashRegister', 5, 1),
('MOD006', 'Mantenedores', 'Catálogos del sistema', 'faTags', 6, 1),
('MOD007', 'Auditoría', 'Historial de cambios', 'faClipboardList', 7, 1),
('MOD008', 'Administración de Módulos', 'Acceso por usuario y rol', 'faCog', 8, 1);

INSERT INTO SUBMODULO (IDSUBMODULO, IDMODULO, NOMBRE, ICONO, ORDEN, ACTIVO) VALUES
('SUB001', 'MOD006', 'Categorías', 'faLayerGroup', 1, 1),
('SUB002', 'MOD006', 'Clientes', 'faIdCard', 2, 1),
('SUB003', 'MOD006', 'Unidades', 'faBox', 3, 1),
('SUB004', 'MOD006', 'Formas de pago', 'faMoneyBill', 4, 1),
('SUB005', 'MOD006', 'Tipos de entrega', 'faTruck', 5, 1);

/* Admin: todos los módulos con todos los permisos */
INSERT INTO GRUPO_MODULO (IDGRUPOMODULO, IDTIPOUSUARIO, IDMODULO, IDTIPOPERMISO)
SELECT 'GRM3' + m.IDMODULO + p.IDTIPOPERMISO, '3', m.IDMODULO, p.IDTIPOPERMISO
FROM MODULO m CROSS JOIN TIPO_PERMISO p;

/* Vendedor: dashboard, productos (ver), cotizaciones, ventas, mantenedores (clientes) */
INSERT INTO GRUPO_MODULO (IDGRUPOMODULO, IDTIPOUSUARIO, IDMODULO, IDTIPOPERMISO)
SELECT 'GRM1' + x.IDMODULO + p.IDTIPOPERMISO, '1', x.IDMODULO, p.IDTIPOPERMISO
FROM (VALUES ('MOD001'),('MOD003'),('MOD004'),('MOD005'),('MOD006')) x(IDMODULO)
CROSS JOIN TIPO_PERMISO p;

/* Almacén: dashboard, productos, mantenedores */
INSERT INTO GRUPO_MODULO (IDGRUPOMODULO, IDTIPOUSUARIO, IDMODULO, IDTIPOPERMISO)
SELECT 'GRM2' + x.IDMODULO + p.IDTIPOPERMISO, '2', x.IDMODULO, p.IDTIPOPERMISO
FROM (VALUES ('MOD001'),('MOD003'),('MOD006')) x(IDMODULO)
CROSS JOIN TIPO_PERMISO p;

INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE, DESCRIPCION, ORDEN, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES
('CAT001', 'Fondant y pastas', 'Coberturas y pastas de modelar', 1, 'Activo', 'sistema', @F, @H, 'sistema', @F, @H),
('CAT002', 'Colorantes', 'Colorantes en gel, polvo y spray', 2, 'Activo', 'sistema', @F, @H, 'sistema', @F, @H),
('CAT003', 'Moldes', 'Moldes de silicón y cortadores', 3, 'Activo', 'sistema', @F, @H, 'sistema', @F, @H);

INSERT INTO UNIDAD (IDUNIDAD, NOMBRE, ABREVIATURA, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES
('UNI001', 'Unidad', 'und', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H),
('UNI002', 'Kilogramo', 'kg', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H),
('UNI003', 'Caja', 'cja', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H);

INSERT INTO FORMA_PAGO (IDFORMAPAGO, NOMBRE, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES
('FPA001', 'Efectivo', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H),
('FPA002', 'Transferencia', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H),
('FPA003', 'Yape / Plin', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H);

INSERT INTO TIPO_ENTREGA (IDTIPOENTREGA, NOMBRE, REQUIEREDIRECCION, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES
('TEN001', 'Recojo en tienda', 0, 'Activo', 'sistema', @F, @H, 'sistema', @F, @H),
('TEN002', 'Delivery', 1, 'Activo', 'sistema', @F, @H, 'sistema', @F, @H);

INSERT INTO CLIENTE (IDCLIENTE, NOMBRE, DOCUMENTO, TELEFONO, EMAIL, DIRECCION, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES
('CLI001', 'Pastelería Dulce Luna', '20123456789', '999111222', 'luna@correo.com', 'Av. Primavera 123', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H);

INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES
('PRD001', 'Fondant blanco 1 kg', 'Pasta de cobertura', 28.50, 40, 'CAT001', 'UNI002', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H),
('PRD002', 'Colorante gel rojo', 'Gel concentrado', 12.00, 80, 'CAT002', 'UNI001', 'Activo', 'sistema', @F, @H, 'sistema', @F, @H);
GO

CREATE PROCEDURE dbo.usp_validate_user
    @username NVARCHAR(50),
    @password NVARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @IDTIPOUSUARIO NVARCHAR(50);

    SELECT @IDTIPOUSUARIO = IDTIPOUSUARIO
    FROM USUARIO
    WHERE IDUSUARIO = @username AND CONTRA = @password AND ESTADO = 'Activo';

    IF @IDTIPOUSUARIO IS NOT NULL
        SELECT CAST(1 AS BIT) AS is_valid,
            CASE @IDTIPOUSUARIO
                WHEN '1' THEN 'vendedor'
                WHEN '2' THEN 'almacen'
                WHEN '3' THEN 'administrador'
                ELSE 'vendedor'
            END AS role;
    ELSE
        SELECT CAST(0 AS BIT) AS is_valid, 'vendedor' AS role;
END;
GO

PRINT 'Esquema DecoCake Shop creado.';
GO
