/* Incremental: módulo Pagos (solo consulta de abonos recientes) */
SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.MODULO WHERE IDMODULO = N'MOD009')
BEGIN
    UPDATE dbo.MODULO SET ORDEN = ORDEN + 1 WHERE ORDEN >= 6;
    INSERT INTO dbo.MODULO (IDMODULO, NOMBRE, DESCRIPCION, ICONO, ORDEN, ACTIVO)
    VALUES (N'MOD009', N'Pagos', N'Pagos y abonos recientes', N'faReceipt', 6, 1);
END
ELSE
BEGIN
    UPDATE dbo.MODULO
    SET NOMBRE = N'Pagos',
        DESCRIPCION = N'Pagos y abonos recientes',
        ICONO = N'faReceipt',
        ACTIVO = 1
    WHERE IDMODULO = N'MOD009';
END
GO

INSERT INTO dbo.GRUPO_MODULO (IDGRUPOMODULO, IDTIPOUSUARIO, IDMODULO, IDTIPOPERMISO)
SELECT N'GRM3MOD009' + p.IDTIPOPERMISO, N'3', N'MOD009', p.IDTIPOPERMISO
FROM dbo.TIPO_PERMISO p
WHERE NOT EXISTS (
    SELECT 1 FROM dbo.GRUPO_MODULO g
    WHERE g.IDTIPOUSUARIO = N'3' AND g.IDMODULO = N'MOD009' AND g.IDTIPOPERMISO = p.IDTIPOPERMISO
);

INSERT INTO dbo.GRUPO_MODULO (IDGRUPOMODULO, IDTIPOUSUARIO, IDMODULO, IDTIPOPERMISO)
SELECT N'GRM1MOD009' + p.IDTIPOPERMISO, N'1', N'MOD009', p.IDTIPOPERMISO
FROM dbo.TIPO_PERMISO p
WHERE NOT EXISTS (
    SELECT 1 FROM dbo.GRUPO_MODULO g
    WHERE g.IDTIPOUSUARIO = N'1' AND g.IDMODULO = N'MOD009' AND g.IDTIPOPERMISO = p.IDTIPOPERMISO
);
GO

IF OBJECT_ID('dbo.usp_pago_listar','P') IS NOT NULL DROP PROCEDURE dbo.usp_pago_listar;
GO
CREATE PROCEDURE dbo.usp_pago_listar
    @Buscar NVARCHAR(200)=NULL, @Tipo NVARCHAR(50)=NULL,
    @OrdenarPor NVARCHAR(50)='FECHA', @Direccion NVARCHAR(4)='DESC',
    @Pagina INT=1, @TamanioPagina INT=10, @TotalRegistros INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    IF @Pagina < 1 SET @Pagina = 1;
    IF @TamanioPagina < 1 SET @TamanioPagina = 10;

    SELECT @TotalRegistros = COUNT(*)
    FROM COTIZACION_PAGO p
    INNER JOIN COTIZACION q ON q.IDCOTIZACION = p.IDCOTIZACION
    LEFT JOIN CLIENTE c ON c.IDCLIENTE = q.IDCLIENTE
    LEFT JOIN FORMA_PAGO f ON f.IDFORMAPAGO = p.IDFORMAPAGO
    WHERE (@Buscar IS NULL OR @Buscar='' OR p.IDPAGO LIKE '%'+@Buscar+'%'
           OR p.IDCOTIZACION LIKE '%'+@Buscar+'%'
           OR ISNULL(c.NOMBRE, q.NOMBRECLIENTE) LIKE '%'+@Buscar+'%'
           OR ISNULL(f.NOMBRE,'') LIKE '%'+@Buscar+'%')
      AND (@Tipo IS NULL OR @Tipo='' OR p.TIPO=@Tipo);

    SELECT p.IDPAGO, p.IDCOTIZACION, ISNULL(c.NOMBRE, q.NOMBRECLIENTE) AS CLIENTE_NOMBRE,
           p.MONTO, p.TIPO, p.IDFORMAPAGO, f.NOMBRE AS FORMAPAGO_NOMBRE,
           q.ESTADO AS COTIZACION_ESTADO, q.IDVENTA,
           p.CREADOPOR,
           ISNULL(NULLIF(LTRIM(RTRIM(ISNULL(cu.NOMBRE,'')+' '+ISNULL(cu.APELLIDO,''))), ''), p.CREADOPOR) AS CREADOPOR_NOMBRE,
           p.FECHACREACION AS FECHA, p.HORACREACION AS HORA
    FROM COTIZACION_PAGO p
    INNER JOIN COTIZACION q ON q.IDCOTIZACION = p.IDCOTIZACION
    LEFT JOIN CLIENTE c ON c.IDCLIENTE = q.IDCLIENTE
    LEFT JOIN FORMA_PAGO f ON f.IDFORMAPAGO = p.IDFORMAPAGO
    LEFT JOIN USUARIO cu ON cu.IDUSUARIO = p.CREADOPOR
    WHERE (@Buscar IS NULL OR @Buscar='' OR p.IDPAGO LIKE '%'+@Buscar+'%'
           OR p.IDCOTIZACION LIKE '%'+@Buscar+'%'
           OR ISNULL(c.NOMBRE, q.NOMBRECLIENTE) LIKE '%'+@Buscar+'%'
           OR ISNULL(f.NOMBRE,'') LIKE '%'+@Buscar+'%')
      AND (@Tipo IS NULL OR @Tipo='' OR p.TIPO=@Tipo)
    ORDER BY
        CASE WHEN @OrdenarPor='IDPAGO' AND @Direccion='ASC' THEN p.IDPAGO END ASC,
        CASE WHEN @OrdenarPor='IDPAGO' AND @Direccion='DESC' THEN p.IDPAGO END DESC,
        CASE WHEN @OrdenarPor='IDCOTIZACION' AND @Direccion='ASC' THEN p.IDCOTIZACION END ASC,
        CASE WHEN @OrdenarPor='IDCOTIZACION' AND @Direccion='DESC' THEN p.IDCOTIZACION END DESC,
        CASE WHEN @OrdenarPor='CLIENTE_NOMBRE' AND @Direccion='ASC' THEN ISNULL(c.NOMBRE, q.NOMBRECLIENTE) END ASC,
        CASE WHEN @OrdenarPor='CLIENTE_NOMBRE' AND @Direccion='DESC' THEN ISNULL(c.NOMBRE, q.NOMBRECLIENTE) END DESC,
        CASE WHEN @OrdenarPor='MONTO' AND @Direccion='ASC' THEN p.MONTO END ASC,
        CASE WHEN @OrdenarPor='MONTO' AND @Direccion='DESC' THEN p.MONTO END DESC,
        CASE WHEN @OrdenarPor='TIPO' AND @Direccion='ASC' THEN p.TIPO END ASC,
        CASE WHEN @OrdenarPor='TIPO' AND @Direccion='DESC' THEN p.TIPO END DESC,
        CASE WHEN @OrdenarPor='FORMAPAGO_NOMBRE' AND @Direccion='ASC' THEN f.NOMBRE END ASC,
        CASE WHEN @OrdenarPor='FORMAPAGO_NOMBRE' AND @Direccion='DESC' THEN f.NOMBRE END DESC,
        CASE WHEN @OrdenarPor='FECHA' AND @Direccion='ASC' THEN p.FECHACREACION END ASC,
        CASE WHEN @OrdenarPor='FECHA' AND @Direccion='DESC' THEN p.FECHACREACION END DESC,
        CASE WHEN @OrdenarPor='HORA' AND @Direccion='ASC' THEN p.HORACREACION END ASC,
        CASE WHEN @OrdenarPor='HORA' AND @Direccion='DESC' THEN p.HORACREACION END DESC,
        p.FECHACREACION DESC, p.HORACREACION DESC, p.IDPAGO DESC
    OFFSET (@Pagina-1)*@TamanioPagina ROWS FETCH NEXT @TamanioPagina ROWS ONLY;
END;
GO

IF OBJECT_ID('dbo.usp_pago_obtener','P') IS NOT NULL DROP PROCEDURE dbo.usp_pago_obtener;
GO
CREATE PROCEDURE dbo.usp_pago_obtener @Id NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT p.IDPAGO, p.IDCOTIZACION, p.MONTO, p.TIPO, p.IDFORMAPAGO, f.NOMBRE AS FORMAPAGO_NOMBRE,
           ISNULL(c.NOMBRE, q.NOMBRECLIENTE) AS CLIENTE_NOMBRE,
           q.ESTADO AS COTIZACION_ESTADO, q.TOTAL AS COTIZACION_TOTAL, q.IDVENTA,
           ISNULL(pay.ABONADO,0) AS ABONADO, q.TOTAL - ISNULL(pay.ABONADO,0) AS SALDO,
           p.CREADOPOR,
           ISNULL(NULLIF(LTRIM(RTRIM(ISNULL(cu.NOMBRE,'')+' '+ISNULL(cu.APELLIDO,''))), ''), p.CREADOPOR) AS CREADOPOR_NOMBRE,
           p.FECHACREACION AS FECHA, p.HORACREACION AS HORA,
           p.MODIFICADOPOR,
           ISNULL(NULLIF(LTRIM(RTRIM(ISNULL(mu.NOMBRE,'')+' '+ISNULL(mu.APELLIDO,''))), ''), p.MODIFICADOPOR) AS MODIFICADOPOR_NOMBRE,
           p.FECHAMODIFICACION, p.HORAMODIFICACION
    FROM COTIZACION_PAGO p
    INNER JOIN COTIZACION q ON q.IDCOTIZACION = p.IDCOTIZACION
    LEFT JOIN CLIENTE c ON c.IDCLIENTE = q.IDCLIENTE
    LEFT JOIN FORMA_PAGO f ON f.IDFORMAPAGO = p.IDFORMAPAGO
    LEFT JOIN USUARIO cu ON cu.IDUSUARIO = p.CREADOPOR
    LEFT JOIN USUARIO mu ON mu.IDUSUARIO = p.MODIFICADOPOR
    OUTER APPLY (SELECT SUM(MONTO) AS ABONADO FROM COTIZACION_PAGO WHERE IDCOTIZACION = q.IDCOTIZACION) pay
    WHERE p.IDPAGO = @Id;
END;
GO

PRINT 'Módulo Pagos listo.';
GO
