/* Incremental: saldo de cotización en listado de pedidos */
SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
GO

IF OBJECT_ID('dbo.usp_venta_listar','P') IS NOT NULL DROP PROCEDURE dbo.usp_venta_listar;
GO
CREATE PROCEDURE dbo.usp_venta_listar
    @Buscar NVARCHAR(200)=NULL, @Estado NVARCHAR(50)=NULL, @OrdenarPor NVARCHAR(50)='FECHA',
    @Direccion NVARCHAR(4)='DESC', @Pagina INT=1, @TamanioPagina INT=10, @TotalRegistros INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT @TotalRegistros = COUNT(*)
    FROM VENTA v LEFT JOIN CLIENTE c ON c.IDCLIENTE=v.IDCLIENTE
    WHERE (@Buscar IS NULL OR @Buscar='' OR v.IDVENTA LIKE '%'+@Buscar+'%' OR ISNULL(c.NOMBRE,v.NOMBRECLIENTE) LIKE '%'+@Buscar+'%' OR ISNULL(v.IDCOTIZACION,'') LIKE '%'+@Buscar+'%')
      AND (@Estado IS NULL OR @Estado='' OR v.ESTADO=@Estado);

    SELECT v.IDVENTA, v.IDCOTIZACION, v.IDCLIENTE, ISNULL(c.NOMBRE, v.NOMBRECLIENTE) AS CLIENTE_NOMBRE, v.NOMBRECLIENTE, v.IDFORMAPAGO, f.NOMBRE AS FORMAPAGO_NOMBRE,
           v.IDTIPOENTREGA, t.NOMBRE AS TIPOENTREGA_NOMBRE, v.DIRECCIONENTREGA, v.COSTODELIVERY, v.SUBTOTAL, v.TOTAL, v.ESTADO,
           v.FECHACREACION AS FECHA, v.HORACREACION AS HORA,
           v.CREADOPOR, LTRIM(RTRIM(ISNULL(cu.NOMBRE,'')+' '+ISNULL(cu.APELLIDO,''))) AS CREADOPOR_NOMBRE,
           ISNULL(pay.ABONADO,0) AS ABONADO,
           CASE WHEN q.IDCOTIZACION IS NULL THEN CAST(0 AS DECIMAL(12,2))
                ELSE q.TOTAL - ISNULL(pay.ABONADO,0) END AS SALDO,
           CASE WHEN q.IDCOTIZACION IS NOT NULL AND (q.TOTAL - ISNULL(pay.ABONADO,0)) > 0.009 THEN 1 ELSE 0 END AS CONDEUDA
    FROM VENTA v
    LEFT JOIN CLIENTE c ON c.IDCLIENTE=v.IDCLIENTE
    LEFT JOIN FORMA_PAGO f ON f.IDFORMAPAGO=v.IDFORMAPAGO
    LEFT JOIN TIPO_ENTREGA t ON t.IDTIPOENTREGA=v.IDTIPOENTREGA
    LEFT JOIN USUARIO cu ON cu.IDUSUARIO=v.CREADOPOR
    LEFT JOIN COTIZACION q ON q.IDCOTIZACION=v.IDCOTIZACION
    OUTER APPLY (SELECT SUM(MONTO) AS ABONADO FROM COTIZACION_PAGO WHERE IDCOTIZACION=v.IDCOTIZACION) pay
    WHERE (@Buscar IS NULL OR @Buscar='' OR v.IDVENTA LIKE '%'+@Buscar+'%' OR ISNULL(c.NOMBRE,v.NOMBRECLIENTE) LIKE '%'+@Buscar+'%' OR ISNULL(v.IDCOTIZACION,'') LIKE '%'+@Buscar+'%')
      AND (@Estado IS NULL OR @Estado='' OR v.ESTADO=@Estado)
    ORDER BY v.FECHACREACION DESC, v.HORACREACION DESC, v.IDVENTA DESC
    OFFSET (@Pagina-1)*@TamanioPagina ROWS FETCH NEXT @TamanioPagina ROWS ONLY;
END;
GO

IF OBJECT_ID('dbo.usp_venta_obtener','P') IS NOT NULL DROP PROCEDURE dbo.usp_venta_obtener;
GO
CREATE PROCEDURE dbo.usp_venta_obtener @Id NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT v.*, ISNULL(c.NOMBRE, v.NOMBRECLIENTE) AS CLIENTE_NOMBRE, f.NOMBRE AS FORMAPAGO_NOMBRE, t.NOMBRE AS TIPOENTREGA_NOMBRE,
           v.FECHACREACION AS FECHA, v.HORACREACION AS HORA,
           ISNULL(pay.ABONADO,0) AS ABONADO,
           CASE WHEN q.IDCOTIZACION IS NULL THEN CAST(0 AS DECIMAL(12,2))
                ELSE q.TOTAL - ISNULL(pay.ABONADO,0) END AS SALDO,
           CASE WHEN q.IDCOTIZACION IS NOT NULL AND (q.TOTAL - ISNULL(pay.ABONADO,0)) > 0.009 THEN 1 ELSE 0 END AS CONDEUDA
    FROM VENTA v
    LEFT JOIN CLIENTE c ON c.IDCLIENTE=v.IDCLIENTE
    LEFT JOIN FORMA_PAGO f ON f.IDFORMAPAGO=v.IDFORMAPAGO
    LEFT JOIN TIPO_ENTREGA t ON t.IDTIPOENTREGA=v.IDTIPOENTREGA
    LEFT JOIN COTIZACION q ON q.IDCOTIZACION=v.IDCOTIZACION
    OUTER APPLY (SELECT SUM(MONTO) AS ABONADO FROM COTIZACION_PAGO WHERE IDCOTIZACION=v.IDCOTIZACION) pay
    WHERE v.IDVENTA=@Id;
END;
GO

PRINT 'Pedidos con saldo de cotización listos.';
GO
