/* Productos extra para el catálogo público */
SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
GO

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE IDPRODUCTO = N'PRD003') AND NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE = N'Colorante gel rosa')
INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES (N'PRD003', N'Colorante gel rosa', N'Gel concentrado tono rosa pastel', 12.00, 70, N'CAT002', N'UNI001', N'Activo', N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108), N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE IDPRODUCTO = N'PRD004') AND NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE = N'Colorante gel amarillo')
INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES (N'PRD004', N'Colorante gel amarillo', N'Gel concentrado para masas y cremas', 12.00, 65, N'CAT002', N'UNI001', N'Activo', N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108), N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE IDPRODUCTO = N'PRD005') AND NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE = N'Fondant negro 1 kg')
INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES (N'PRD005', N'Fondant negro 1 kg', N'Pasta de cobertura color intenso', 29.50, 35, N'CAT001', N'UNI002', N'Activo', N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108), N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE IDPRODUCTO = N'PRD006') AND NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE = N'Pasta de goma 500 g')
INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES (N'PRD006', N'Pasta de goma 500 g', N'Para modelado de figuras y flores', 18.00, 40, N'CAT001', N'UNI001', N'Activo', N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108), N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE IDPRODUCTO = N'PRD007') AND NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE = N'Molde silicona cupcake')
INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES (N'PRD007', N'Molde silicona cupcake', N'12 cavidades, antiadherente', 22.00, 28, N'CAT003', N'UNI001', N'Activo', N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108), N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE IDPRODUCTO = N'PRD008') AND NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE = N'Cortador flor set')
INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES (N'PRD008', N'Cortador flor set', N'Set de 6 cortadores para fondant', 15.50, 45, N'CAT003', N'UNI001', N'Activo', N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108), N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE IDPRODUCTO = N'PRD009') AND NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE = N'Molde número 3D')
INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES (N'PRD009', N'Molde número 3D', N'Molde para tortas numéricas', 19.90, 22, N'CAT003', N'UNI001', N'Activo', N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108), N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE IDPRODUCTO = N'PRD010') AND NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE = N'Sprinkles perlados 100 g')
INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IDCATEGORIA, IDUNIDAD, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES (N'PRD010', N'Sprinkles perlados 100 g', N'Perlas comestibles para decoración', 8.50, 90, N'CAT001', N'UNI001', N'Activo', N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108), N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108));
GO

PRINT 'Productos de catálogo listos.';
GO
