/* Productos e imágenes de la tienda pública */
SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
GO

IF NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE IDCATEGORIA=N'CAT004')
INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE, DESCRIPCION, ORDEN, ESTADO, CREADOPOR, FECHACREACION, HORACREACION, MODIFICADOPOR, FECHAMODIFICACION, HORAMODIFICACION)
VALUES (N'CAT004', N'Utensilios', N'Rodillos, balanzas y accesorios de trabajo', 4, N'Activo', N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108), N'sistema', dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108));
GO

UPDATE PRODUCTO SET FOTO=N'/shop-products/04-taper-bombonera.png' WHERE IDPRODUCTO=N'PRD001' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO=N'/shop-products/03-sorbetones.png' WHERE IDPRODUCTO=N'PRD002' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO=N'/shop-products/03-sorbetones.png' WHERE IDPRODUCTO=N'PRD003' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO=N'/shop-products/03-sorbetones.png' WHERE IDPRODUCTO=N'PRD004' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO=N'/shop-products/04-taper-bombonera.png' WHERE IDPRODUCTO=N'PRD005' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO=N'/shop-products/02-estatulas-x3-und.jpeg' WHERE IDPRODUCTO=N'PRD006' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO=N'/shop-products/12-kekera-rectangular-x5-und.jpeg' WHERE IDPRODUCTO=N'PRD007' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO=N'/shop-products/01-cortador-y-alisador.png' WHERE IDPRODUCTO=N'PRD008' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO=N'/shop-products/17-molde-keke-ingles-x3-und.jpeg' WHERE IDPRODUCTO=N'PRD009' AND (FOTO IS NULL OR FOTO='');
UPDATE PRODUCTO SET FOTO=N'/shop-products/03-sorbetones.png' WHERE IDPRODUCTO=N'PRD010' AND (FOTO IS NULL OR FOTO='');
GO

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Cortador y alisador')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD011',N'Cortador y alisador',N'Cortador y alisador para fondant',12.00,40,N'CAT003',N'UNI001',N'Activo',N'/shop-products/01-cortador-y-alisador.png',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Espátulas x3 und')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD012',N'Espátulas x3 und',N'Espátulas por 3 unidades',8.00,50,N'CAT004',N'UNI001',N'Activo',N'/shop-products/02-estatulas-x3-und.jpeg',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Sorbetones x50 und')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD013',N'Sorbetones x50 und',N'Sorbetones por 50 unidades',7.00,80,N'CAT004',N'UNI001',N'Activo',N'/shop-products/03-sorbetones.png',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Taper bombonera')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD014',N'Taper bombonera',N'Tapa alta. Material PET. Medida: 8 onz.',35.00,25,N'CAT004',N'UNI001',N'Activo',N'/shop-products/04-taper-bombonera.png',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Bowls de acero x7 und')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD015',N'Bowls de acero x7 und',N'Set de 7 bowls metálicos. Medidas 18/20/22/24/26/28/30 cm.',58.00,18,N'CAT004',N'UNI001',N'Activo',N'/shop-products/05-bols-de-acero-x7und.png',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Rodillo de acero 40 cm')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD016',N'Rodillo de acero 40 cm',N'Rodillo de acero con medidas',18.00,30,N'CAT004',N'UNI001',N'Activo',N'/shop-products/06-rodillo-de-acero-40-cm.png',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Rodillo acrílico 23 cm')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD017',N'Rodillo acrílico 23 cm',N'Rodillo acrílico de 23 cm',8.00,35,N'CAT004',N'UNI001',N'Activo',N'/shop-products/07-rodillo-acrilico-23-cm.png',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Rodillo acrílico 40 cm')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD018',N'Rodillo acrílico 40 cm',N'Rodillo acrílico 40 cm',15.00,28,N'CAT004',N'UNI001',N'Activo',N'/shop-products/08-rodillo-acrilico-40-cm.png',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Rodillo acrílico 50 cm')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD019',N'Rodillo acrílico 50 cm',N'Rodillo acrílico 50 cm',19.00,22,N'CAT004',N'UNI001',N'Activo',N'/shop-products/09-rodillo-en-acrilico-50-cm.png',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Mini gramera')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD020',N'Mini gramera',N'Mini gramera de precisión',15.00,40,N'CAT004',N'UNI001',N'Activo',N'/shop-products/10-mini-gramera.png',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Balanza clásica')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD021',N'Balanza clásica',N'Balanza clásica hasta 5 kg. Color rosada.',12.00,26,N'CAT004',N'UNI001',N'Activo',N'/shop-products/11-balanza-clasica.png',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Kekera rectangular x5 und')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD022',N'Kekera rectangular x5 und',N'Set de 5 kekeras rectangulares',32.00,16,N'CAT003',N'UNI001',N'Activo',N'/shop-products/12-kekera-rectangular-x5-und.jpeg',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Balanza de corazón')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD023',N'Balanza de corazón',N'Balanza de corazón hasta 5 kg',25.00,20,N'CAT004',N'UNI001',N'Activo',N'/shop-products/13-balanza-de-corazon.png',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Balanza de vidrio')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD024',N'Balanza de vidrio',N'Balanza de vidrio hasta 5 kg',20.00,18,N'CAT004',N'UNI001',N'Activo',N'/shop-products/14-balanza-de-vidrio.png',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Kekera corazón x5 und')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD025',N'Kekera corazón x5 und',N'Set de 5 kekeras en forma de corazón',32.00,14,N'CAT003',N'UNI001',N'Activo',N'/shop-products/15-kekera-coraz-n-x5-und.jpeg',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Kekeras cuadradas x5 und')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD026',N'Kekeras cuadradas x5 und',N'Medidas 15, 20, 25, 30 y 35 cm',32.00,14,N'CAT003',N'UNI001',N'Activo',N'/shop-products/16-kekeras-cuadradas-x5-und.jpeg',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Molde keke inglés x3 und')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD027',N'Molde keke inglés x3 und',N'Medidas 22x11, 28x11 y 32x11 cm',14.00,20,N'CAT003',N'UNI001',N'Activo',N'/shop-products/17-molde-keke-ingles-x3-und.jpeg',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));

IF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE NOMBRE=N'Terrinas x3 unidades')
INSERT INTO PRODUCTO (IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO,STOCK,IDCATEGORIA,IDUNIDAD,ESTADO,FOTO,CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
VALUES (N'PRD028',N'Terrinas x3 unidades',N'15, 18 y 25 tajadas',26.00,16,N'CAT003',N'UNI001',N'Activo',N'/shop-products/18-terrinas-x3-unidades.jpeg',N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),N'sistema',dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));
GO

PRINT 'Productos de tienda con fotos listos.';
GO
