SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
GO

IF OBJECT_ID('dbo.usp_cotizacion_listar','P') IS NOT NULL DROP PROCEDURE dbo.usp_cotizacion_listar;
GO
CREATE PROCEDURE dbo.usp_cotizacion_listar
    @Buscar NVARCHAR(200)=NULL, @Estado NVARCHAR(50)=NULL, @OrdenarPor NVARCHAR(50)='FECHA',
    @Direccion NVARCHAR(4)='DESC', @Pagina INT=1, @TamanioPagina INT=10, @TotalRegistros INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT @TotalRegistros = COUNT(*)
    FROM COTIZACION q
    LEFT JOIN CLIENTE c ON c.IDCLIENTE=q.IDCLIENTE
    WHERE (@Buscar IS NULL OR @Buscar='' OR q.IDCOTIZACION LIKE '%'+@Buscar+'%'
           OR ISNULL(c.NOMBRE,q.NOMBRECLIENTE) LIKE '%'+@Buscar+'%')
      AND (@Estado IS NULL OR @Estado='' OR q.ESTADO=@Estado);

    SELECT q.IDCOTIZACION, q.IDCLIENTE, ISNULL(c.NOMBRE, q.NOMBRECLIENTE) AS CLIENTE_NOMBRE, q.NOMBRECLIENTE,
           q.IDTIPOENTREGA, t.NOMBRE AS TIPOENTREGA_NOMBRE,
           q.DIRECCIONENTREGA, q.COSTODELIVERY, q.SUBTOTAL, q.TOTAL, q.ESTADO, q.IDVENTA,
           q.FECHACREACION AS FECHA, q.HORACREACION AS HORA,
           q.CREADOPOR, LTRIM(RTRIM(ISNULL(cu.NOMBRE,'')+' '+ISNULL(cu.APELLIDO,''))) AS CREADOPOR_NOMBRE,
           q.MODIFICADOPOR, q.FECHAMODIFICACION, q.HORAMODIFICACION
    FROM COTIZACION q
    LEFT JOIN CLIENTE c ON c.IDCLIENTE=q.IDCLIENTE
    LEFT JOIN TIPO_ENTREGA t ON t.IDTIPOENTREGA=q.IDTIPOENTREGA
    LEFT JOIN USUARIO cu ON cu.IDUSUARIO=q.CREADOPOR
    WHERE (@Buscar IS NULL OR @Buscar='' OR q.IDCOTIZACION LIKE '%'+@Buscar+'%'
           OR ISNULL(c.NOMBRE,q.NOMBRECLIENTE) LIKE '%'+@Buscar+'%')
      AND (@Estado IS NULL OR @Estado='' OR q.ESTADO=@Estado)
    ORDER BY q.FECHACREACION DESC, q.HORACREACION DESC, q.IDCOTIZACION DESC
    OFFSET (@Pagina-1)*@TamanioPagina ROWS FETCH NEXT @TamanioPagina ROWS ONLY;
END;
GO

IF OBJECT_ID('dbo.usp_cotizacion_obtener','P') IS NOT NULL DROP PROCEDURE dbo.usp_cotizacion_obtener;
GO
CREATE PROCEDURE dbo.usp_cotizacion_obtener @Id NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT q.*, ISNULL(c.NOMBRE, q.NOMBRECLIENTE) AS CLIENTE_NOMBRE, t.NOMBRE AS TIPOENTREGA_NOMBRE, t.REQUIEREDIRECCION,
           q.FECHACREACION AS FECHA, q.HORACREACION AS HORA
    FROM COTIZACION q
    LEFT JOIN CLIENTE c ON c.IDCLIENTE=q.IDCLIENTE
    LEFT JOIN TIPO_ENTREGA t ON t.IDTIPOENTREGA=q.IDTIPOENTREGA
    WHERE q.IDCOTIZACION=@Id;
END;
GO

IF OBJECT_ID('dbo.usp_cotizacion_detalle_listar','P') IS NOT NULL DROP PROCEDURE dbo.usp_cotizacion_detalle_listar;
GO
CREATE PROCEDURE dbo.usp_cotizacion_detalle_listar @Id NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT d.IDDETALLE, d.IDPRODUCTO, p.NOMBRE AS PRODUCTO_NOMBRE, d.CANTIDAD, d.PRECIOUNITARIO, d.SUBTOTAL, p.STOCK
    FROM COTIZACION_DETALLE d INNER JOIN PRODUCTO p ON p.IDPRODUCTO=d.IDPRODUCTO
    WHERE d.IDCOTIZACION=@Id;
END;
GO

IF OBJECT_ID('dbo.usp_cotizacion_guardar_detalle','P') IS NOT NULL DROP PROCEDURE dbo.usp_cotizacion_guardar_detalle;
GO
CREATE PROCEDURE dbo.usp_cotizacion_guardar_detalle @Id NVARCHAR(50), @DetalleJson NVARCHAR(MAX)
AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM COTIZACION_DETALLE WHERE IDCOTIZACION=@Id;
    DECLARE @n INT = 0;
    INSERT INTO COTIZACION_DETALLE (IDDETALLE, IDCOTIZACION, IDPRODUCTO, CANTIDAD, PRECIOUNITARIO, SUBTOTAL)
    SELECT @Id + RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY j.IDPRODUCTO) AS VARCHAR(4)), 3),
           @Id, j.IDPRODUCTO, j.CANTIDAD, j.PRECIOUNITARIO, j.CANTIDAD * j.PRECIOUNITARIO
    FROM OPENJSON(@DetalleJson) WITH (
        IDPRODUCTO NVARCHAR(50) '$.IDPRODUCTO',
        CANTIDAD DECIMAL(12,2) '$.CANTIDAD',
        PRECIOUNITARIO DECIMAL(12,2) '$.PRECIOUNITARIO'
    ) j
    WHERE j.IDPRODUCTO IS NOT NULL AND j.CANTIDAD > 0;

    DECLARE @Sub DECIMAL(12,2) = ISNULL((SELECT SUM(SUBTOTAL) FROM COTIZACION_DETALLE WHERE IDCOTIZACION=@Id),0);
    UPDATE COTIZACION SET SUBTOTAL=@Sub, TOTAL=@Sub + ISNULL(COSTODELIVERY,0) WHERE IDCOTIZACION=@Id;
END;
GO

IF OBJECT_ID('dbo.usp_cotizacion_insertar','P') IS NOT NULL DROP PROCEDURE dbo.usp_cotizacion_insertar;
GO
CREATE PROCEDURE dbo.usp_cotizacion_insertar
    @IdCliente NVARCHAR(50)=NULL, @NombreCliente NVARCHAR(200)=NULL, @IdTipoEntrega NVARCHAR(50)=NULL,
    @DireccionEntrega NVARCHAR(255)=NULL, @CostoDelivery DECIMAL(12,2)=0, @Observaciones NVARCHAR(MAX)=NULL,
    @Estado NVARCHAR(50)='Cotizado', @DetalleJson NVARCHAR(MAX)=NULL,
    @Resultado INT OUTPUT, @Mensaje NVARCHAR(200) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @IdCli NVARCHAR(50) = NULLIF(LTRIM(RTRIM(ISNULL(@IdCliente,''))), '');
    DECLARE @Nom NVARCHAR(200) = NULLIF(LTRIM(RTRIM(ISNULL(@NombreCliente,''))), '');
    IF @IdCli IS NOT NULL AND EXISTS (SELECT 1 FROM CLIENTE WHERE IDCLIENTE=@IdCli)
        SELECT @Nom = ISNULL(@Nom, NOMBRE) FROM CLIENTE WHERE IDCLIENTE=@IdCli;
    ELSE
        SET @IdCli = NULL;
    IF @Nom IS NULL BEGIN SET @Resultado=0; SET @Mensaje='Ingresa el cliente.'; RETURN; END
    DECLARE @Id NVARCHAR(50); EXEC dbo.usp_siguiente_id 'COT','COTIZACION','IDCOTIZACION',@Id OUTPUT;
    INSERT INTO COTIZACION (IDCOTIZACION,IDCLIENTE,NOMBRECLIENTE,IDTIPOENTREGA,DIRECCIONENTREGA,COSTODELIVERY,SUBTOTAL,TOTAL,OBSERVACIONES,ESTADO,
        CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
    VALUES (@Id,@IdCli,@Nom,@IdTipoEntrega,@DireccionEntrega,ISNULL(@CostoDelivery,0),0,0,@Observaciones,ISNULL(@Estado,'Cotizado'),
        dbo.fn_actor(),dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),dbo.fn_actor(),dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));
    IF @DetalleJson IS NOT NULL AND LEN(@DetalleJson)>2
        EXEC dbo.usp_cotizacion_guardar_detalle @Id, @DetalleJson;
    SET @Resultado=1; SET @Mensaje='Cotización registrada.';
END;
GO

IF OBJECT_ID('dbo.usp_cotizacion_actualizar','P') IS NOT NULL DROP PROCEDURE dbo.usp_cotizacion_actualizar;
GO
CREATE PROCEDURE dbo.usp_cotizacion_actualizar
    @Id NVARCHAR(50), @IdCliente NVARCHAR(50)=NULL, @NombreCliente NVARCHAR(200)=NULL, @IdTipoEntrega NVARCHAR(50)=NULL,
    @DireccionEntrega NVARCHAR(255)=NULL, @CostoDelivery DECIMAL(12,2)=0, @Observaciones NVARCHAR(MAX)=NULL,
    @Estado NVARCHAR(50)='Cotizado', @DetalleJson NVARCHAR(MAX)=NULL,
    @Resultado INT OUTPUT, @Mensaje NVARCHAR(200) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    IF NOT EXISTS (SELECT 1 FROM COTIZACION WHERE IDCOTIZACION=@Id) BEGIN SET @Resultado=0; SET @Mensaje='La cotización no existe.'; RETURN; END
    IF EXISTS (SELECT 1 FROM COTIZACION WHERE IDCOTIZACION=@Id AND ESTADO IN ('Convertida','Anulada'))
    BEGIN SET @Resultado=0; SET @Mensaje='No se puede editar una cotización convertida o anulada.'; RETURN; END
    DECLARE @IdCli NVARCHAR(50) = NULLIF(LTRIM(RTRIM(ISNULL(@IdCliente,''))), '');
    DECLARE @Nom NVARCHAR(200) = NULLIF(LTRIM(RTRIM(ISNULL(@NombreCliente,''))), '');
    IF @IdCli IS NOT NULL AND EXISTS (SELECT 1 FROM CLIENTE WHERE IDCLIENTE=@IdCli)
        SELECT @Nom = ISNULL(@Nom, NOMBRE) FROM CLIENTE WHERE IDCLIENTE=@IdCli;
    ELSE
        SET @IdCli = NULL;
    IF @Nom IS NULL BEGIN SET @Resultado=0; SET @Mensaje='Ingresa el cliente.'; RETURN; END
    UPDATE COTIZACION SET IDCLIENTE=@IdCli, NOMBRECLIENTE=@Nom, IDTIPOENTREGA=@IdTipoEntrega, DIRECCIONENTREGA=@DireccionEntrega,
        COSTODELIVERY=ISNULL(@CostoDelivery,0), OBSERVACIONES=@Observaciones, ESTADO=@Estado,
        MODIFICADOPOR=dbo.fn_actor(), FECHAMODIFICACION=dbo.fn_fecha_ddmmyyyy(), HORAMODIFICACION=CONVERT(CHAR(8),GETDATE(),108)
    WHERE IDCOTIZACION=@Id;
    IF @DetalleJson IS NOT NULL
        EXEC dbo.usp_cotizacion_guardar_detalle @Id, @DetalleJson;
    SET @Resultado=1; SET @Mensaje='Cotización actualizada.';
END;
GO

IF OBJECT_ID('dbo.usp_cotizacion_eliminar','P') IS NOT NULL DROP PROCEDURE dbo.usp_cotizacion_eliminar;
GO
CREATE PROCEDURE dbo.usp_cotizacion_eliminar @Id NVARCHAR(50), @Resultado INT OUTPUT, @Mensaje NVARCHAR(200) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM COTIZACION WHERE IDCOTIZACION=@Id AND ESTADO='Convertida')
    BEGIN SET @Resultado=0; SET @Mensaje='No se puede eliminar: ya fue convertida a venta.'; RETURN; END
    DELETE FROM COTIZACION_DETALLE WHERE IDCOTIZACION=@Id;
    DELETE FROM COTIZACION WHERE IDCOTIZACION=@Id;
    SET @Resultado=1; SET @Mensaje='Cotización eliminada.';
END;
GO

IF OBJECT_ID('dbo.usp_cotizacion_hacer_pedido','P') IS NOT NULL DROP PROCEDURE dbo.usp_cotizacion_hacer_pedido;
GO
CREATE PROCEDURE dbo.usp_cotizacion_hacer_pedido
    @Id NVARCHAR(50),
    @IdFormaPago NVARCHAR(50)=NULL,
    @IdTipoEntrega NVARCHAR(50)=NULL,
    @DireccionEntrega NVARCHAR(255)=NULL,
    @CostoDelivery DECIMAL(12,2)=0,
    @Resultado INT OUTPUT, @Mensaje NVARCHAR(200) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    IF NOT EXISTS (SELECT 1 FROM COTIZACION WHERE IDCOTIZACION=@Id)
    BEGIN SET @Resultado=0; SET @Mensaje='La cotización no existe.'; RETURN; END
    IF EXISTS (SELECT 1 FROM COTIZACION WHERE IDCOTIZACION=@Id AND ESTADO IN ('Convertida','Anulada'))
    BEGIN SET @Resultado=0; SET @Mensaje='La cotización ya fue convertida o está anulada.'; RETURN; END
    IF NOT EXISTS (SELECT 1 FROM COTIZACION_DETALLE WHERE IDCOTIZACION=@Id)
    BEGIN SET @Resultado=0; SET @Mensaje='La cotización no tiene productos.'; RETURN; END

    DECLARE @Tipo NVARCHAR(50) = NULLIF(LTRIM(RTRIM(ISNULL(@IdTipoEntrega,''))), '');
    IF @Tipo IS NULL OR NOT EXISTS (SELECT 1 FROM TIPO_ENTREGA WHERE IDTIPOENTREGA=@Tipo AND ESTADO='Activo')
    BEGIN SET @Resultado=0; SET @Mensaje='Selecciona el tipo de entrega.'; RETURN; END
    IF EXISTS (SELECT 1 FROM TIPO_ENTREGA WHERE IDTIPOENTREGA=@Tipo AND REQUIEREDIRECCION=1)
       AND NULLIF(LTRIM(RTRIM(ISNULL(@DireccionEntrega,''))),'') IS NULL
    BEGIN SET @Resultado=0; SET @Mensaje='Ingresa la dirección de delivery.'; RETURN; END

    IF EXISTS (
        SELECT 1 FROM COTIZACION_DETALLE d INNER JOIN PRODUCTO p ON p.IDPRODUCTO=d.IDPRODUCTO
        WHERE d.IDCOTIZACION=@Id AND p.STOCK < d.CANTIDAD
    )
    BEGIN SET @Resultado=0; SET @Mensaje='Stock insuficiente para uno o más productos.'; RETURN; END

    DECLARE @IdVenta NVARCHAR(50); EXEC dbo.usp_siguiente_id 'VEN','VENTA','IDVENTA',@IdVenta OUTPUT;
    DECLARE @Sub DECIMAL(12,2), @Cli NVARCHAR(50), @Nom NVARCHAR(200), @Obs NVARCHAR(MAX);
    SELECT @Sub = SUBTOTAL, @Cli = IDCLIENTE, @Nom = NOMBRECLIENTE, @Obs = OBSERVACIONES
    FROM COTIZACION WHERE IDCOTIZACION=@Id;

    INSERT INTO VENTA (IDVENTA,IDCOTIZACION,IDCLIENTE,NOMBRECLIENTE,IDFORMAPAGO,IDTIPOENTREGA,DIRECCIONENTREGA,COSTODELIVERY,SUBTOTAL,TOTAL,OBSERVACIONES,ESTADO,
        CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
    VALUES (
        @IdVenta, @Id, @Cli, @Nom, NULLIF(LTRIM(RTRIM(ISNULL(@IdFormaPago,''))), ''), @Tipo, @DireccionEntrega,
        ISNULL(@CostoDelivery,0), @Sub, @Sub + ISNULL(@CostoDelivery,0), @Obs, 'Pagado',
        dbo.fn_actor(), dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108),
        dbo.fn_actor(), dbo.fn_fecha_ddmmyyyy(), CONVERT(CHAR(8),GETDATE(),108)
    );

    INSERT INTO VENTA_DETALLE (IDDETALLE, IDVENTA, IDPRODUCTO, CANTIDAD, PRECIOUNITARIO, SUBTOTAL)
    SELECT @IdVenta + RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY IDDETALLE) AS VARCHAR(4)), 3),
           @IdVenta, IDPRODUCTO, CANTIDAD, PRECIOUNITARIO, SUBTOTAL
    FROM COTIZACION_DETALLE WHERE IDCOTIZACION=@Id;

    UPDATE p SET p.STOCK = p.STOCK - d.CANTIDAD,
        p.MODIFICADOPOR=dbo.fn_actor(), p.FECHAMODIFICACION=dbo.fn_fecha_ddmmyyyy(), p.HORAMODIFICACION=CONVERT(CHAR(8),GETDATE(),108)
    FROM PRODUCTO p INNER JOIN COTIZACION_DETALLE d ON d.IDPRODUCTO=p.IDPRODUCTO
    WHERE d.IDCOTIZACION=@Id;

    UPDATE COTIZACION SET ESTADO='Convertida', IDVENTA=@IdVenta,
        IDTIPOENTREGA=@Tipo, DIRECCIONENTREGA=@DireccionEntrega, COSTODELIVERY=ISNULL(@CostoDelivery,0),
        TOTAL=@Sub + ISNULL(@CostoDelivery,0),
        MODIFICADOPOR=dbo.fn_actor(), FECHAMODIFICACION=dbo.fn_fecha_ddmmyyyy(), HORAMODIFICACION=CONVERT(CHAR(8),GETDATE(),108)
    WHERE IDCOTIZACION=@Id;

    SET @Resultado=1; SET @Mensaje='Pedido generado. '+@IdVenta+'.';
END;
GO

/* VENTAS */
IF OBJECT_ID('dbo.usp_venta_listar','P') IS NOT NULL DROP PROCEDURE dbo.usp_venta_listar;
GO
CREATE PROCEDURE dbo.usp_venta_listar
    @Buscar NVARCHAR(200)=NULL, @Estado NVARCHAR(50)=NULL, @OrdenarPor NVARCHAR(50)='FECHA',
    @Direccion NVARCHAR(4)='DESC', @Pagina INT=1, @TamanioPagina INT=10, @TotalRegistros INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT @TotalRegistros = COUNT(*)
    FROM VENTA v LEFT JOIN CLIENTE c ON c.IDCLIENTE=v.IDCLIENTE
    WHERE (@Buscar IS NULL OR @Buscar='' OR v.IDVENTA LIKE '%'+@Buscar+'%' OR ISNULL(c.NOMBRE,v.NOMBRECLIENTE) LIKE '%'+@Buscar+'%' OR ISNULL(v.IDCOTIZACION,'') LIKE '%'+@Buscar+'%')
      AND (@Estado IS NULL OR @Estado='' OR v.ESTADO=@Estado);

    SELECT v.IDVENTA, v.IDCOTIZACION, v.IDCLIENTE, ISNULL(c.NOMBRE, v.NOMBRECLIENTE) AS CLIENTE_NOMBRE, v.NOMBRECLIENTE, v.IDFORMAPAGO, f.NOMBRE AS FORMAPAGO_NOMBRE,
           v.IDTIPOENTREGA, t.NOMBRE AS TIPOENTREGA_NOMBRE, v.DIRECCIONENTREGA, v.COSTODELIVERY, v.SUBTOTAL, v.TOTAL, v.ESTADO,
           v.FECHACREACION AS FECHA, v.HORACREACION AS HORA,
           v.CREADOPOR, LTRIM(RTRIM(ISNULL(cu.NOMBRE,'')+' '+ISNULL(cu.APELLIDO,''))) AS CREADOPOR_NOMBRE
    FROM VENTA v
    LEFT JOIN CLIENTE c ON c.IDCLIENTE=v.IDCLIENTE
    LEFT JOIN FORMA_PAGO f ON f.IDFORMAPAGO=v.IDFORMAPAGO
    LEFT JOIN TIPO_ENTREGA t ON t.IDTIPOENTREGA=v.IDTIPOENTREGA
    LEFT JOIN USUARIO cu ON cu.IDUSUARIO=v.CREADOPOR
    WHERE (@Buscar IS NULL OR @Buscar='' OR v.IDVENTA LIKE '%'+@Buscar+'%' OR ISNULL(c.NOMBRE,v.NOMBRECLIENTE) LIKE '%'+@Buscar+'%' OR ISNULL(v.IDCOTIZACION,'') LIKE '%'+@Buscar+'%')
      AND (@Estado IS NULL OR @Estado='' OR v.ESTADO=@Estado)
    ORDER BY v.FECHACREACION DESC, v.HORACREACION DESC
    OFFSET (@Pagina-1)*@TamanioPagina ROWS FETCH NEXT @TamanioPagina ROWS ONLY;
END;
GO

IF OBJECT_ID('dbo.usp_venta_obtener','P') IS NOT NULL DROP PROCEDURE dbo.usp_venta_obtener;
GO
CREATE PROCEDURE dbo.usp_venta_obtener @Id NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT v.*, ISNULL(c.NOMBRE, v.NOMBRECLIENTE) AS CLIENTE_NOMBRE, f.NOMBRE AS FORMAPAGO_NOMBRE, t.NOMBRE AS TIPOENTREGA_NOMBRE,
           v.FECHACREACION AS FECHA, v.HORACREACION AS HORA
    FROM VENTA v
    LEFT JOIN CLIENTE c ON c.IDCLIENTE=v.IDCLIENTE
    LEFT JOIN FORMA_PAGO f ON f.IDFORMAPAGO=v.IDFORMAPAGO
    LEFT JOIN TIPO_ENTREGA t ON t.IDTIPOENTREGA=v.IDTIPOENTREGA
    WHERE v.IDVENTA=@Id;
END;
GO

IF OBJECT_ID('dbo.usp_venta_detalle_listar','P') IS NOT NULL DROP PROCEDURE dbo.usp_venta_detalle_listar;
GO
CREATE PROCEDURE dbo.usp_venta_detalle_listar @Id NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT d.IDDETALLE, d.IDPRODUCTO, p.NOMBRE AS PRODUCTO_NOMBRE, d.CANTIDAD, d.PRECIOUNITARIO, d.SUBTOTAL
    FROM VENTA_DETALLE d INNER JOIN PRODUCTO p ON p.IDPRODUCTO=d.IDPRODUCTO
    WHERE d.IDVENTA=@Id;
END;
GO

IF OBJECT_ID('dbo.usp_venta_guardar_detalle','P') IS NOT NULL DROP PROCEDURE dbo.usp_venta_guardar_detalle;
GO
CREATE PROCEDURE dbo.usp_venta_guardar_detalle @Id NVARCHAR(50), @DetalleJson NVARCHAR(MAX)
AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM VENTA_DETALLE WHERE IDVENTA=@Id;
    INSERT INTO VENTA_DETALLE (IDDETALLE, IDVENTA, IDPRODUCTO, CANTIDAD, PRECIOUNITARIO, SUBTOTAL)
    SELECT @Id + RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY j.IDPRODUCTO) AS VARCHAR(4)), 3),
           @Id, j.IDPRODUCTO, j.CANTIDAD, j.PRECIOUNITARIO, j.CANTIDAD * j.PRECIOUNITARIO
    FROM OPENJSON(@DetalleJson) WITH (
        IDPRODUCTO NVARCHAR(50) '$.IDPRODUCTO',
        CANTIDAD DECIMAL(12,2) '$.CANTIDAD',
        PRECIOUNITARIO DECIMAL(12,2) '$.PRECIOUNITARIO'
    ) j WHERE j.IDPRODUCTO IS NOT NULL AND j.CANTIDAD > 0;
    DECLARE @Sub DECIMAL(12,2) = ISNULL((SELECT SUM(SUBTOTAL) FROM VENTA_DETALLE WHERE IDVENTA=@Id),0);
    UPDATE VENTA SET SUBTOTAL=@Sub, TOTAL=@Sub + ISNULL(COSTODELIVERY,0) WHERE IDVENTA=@Id;
END;
GO

IF OBJECT_ID('dbo.usp_venta_insertar','P') IS NOT NULL DROP PROCEDURE dbo.usp_venta_insertar;
GO
CREATE PROCEDURE dbo.usp_venta_insertar
    @IdCliente NVARCHAR(50), @IdFormaPago NVARCHAR(50)=NULL, @IdTipoEntrega NVARCHAR(50)=NULL,
    @DireccionEntrega NVARCHAR(255)=NULL, @CostoDelivery DECIMAL(12,2)=0, @Observaciones NVARCHAR(MAX)=NULL,
    @Estado NVARCHAR(50)='Pagado', @DetalleJson NVARCHAR(MAX)=NULL,
    @Resultado INT OUTPUT, @Mensaje NVARCHAR(200) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    IF @IdCliente IS NULL BEGIN SET @Resultado=0; SET @Mensaje='Selecciona un cliente.'; RETURN; END
    DECLARE @Id NVARCHAR(50); EXEC dbo.usp_siguiente_id 'VEN','VENTA','IDVENTA',@Id OUTPUT;
    INSERT INTO VENTA (IDVENTA,IDCLIENTE,IDFORMAPAGO,IDTIPOENTREGA,DIRECCIONENTREGA,COSTODELIVERY,SUBTOTAL,TOTAL,OBSERVACIONES,ESTADO,
        CREADOPOR,FECHACREACION,HORACREACION,MODIFICADOPOR,FECHAMODIFICACION,HORAMODIFICACION)
    VALUES (@Id,@IdCliente,@IdFormaPago,@IdTipoEntrega,@DireccionEntrega,ISNULL(@CostoDelivery,0),0,0,@Observaciones,ISNULL(@Estado,'Pagado'),
        dbo.fn_actor(),dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108),dbo.fn_actor(),dbo.fn_fecha_ddmmyyyy(),CONVERT(CHAR(8),GETDATE(),108));
    IF @DetalleJson IS NOT NULL AND LEN(@DetalleJson)>2
        EXEC dbo.usp_venta_guardar_detalle @Id, @DetalleJson;
    SET @Resultado=1; SET @Mensaje='Venta registrada.';
END;
GO

IF OBJECT_ID('dbo.usp_venta_actualizar','P') IS NOT NULL DROP PROCEDURE dbo.usp_venta_actualizar;
GO
CREATE PROCEDURE dbo.usp_venta_actualizar
    @Id NVARCHAR(50), @IdCliente NVARCHAR(50), @IdFormaPago NVARCHAR(50)=NULL, @IdTipoEntrega NVARCHAR(50)=NULL,
    @DireccionEntrega NVARCHAR(255)=NULL, @CostoDelivery DECIMAL(12,2)=0, @Observaciones NVARCHAR(MAX)=NULL,
    @Estado NVARCHAR(50)='Pagado', @DetalleJson NVARCHAR(MAX)=NULL,
    @Resultado INT OUTPUT, @Mensaje NVARCHAR(200) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    IF NOT EXISTS (SELECT 1 FROM VENTA WHERE IDVENTA=@Id) BEGIN SET @Resultado=0; SET @Mensaje='La venta no existe.'; RETURN; END
    UPDATE VENTA SET IDCLIENTE=@IdCliente, IDFORMAPAGO=@IdFormaPago, IDTIPOENTREGA=@IdTipoEntrega,
        DIRECCIONENTREGA=@DireccionEntrega, COSTODELIVERY=ISNULL(@CostoDelivery,0), OBSERVACIONES=@Observaciones, ESTADO=@Estado,
        MODIFICADOPOR=dbo.fn_actor(), FECHAMODIFICACION=dbo.fn_fecha_ddmmyyyy(), HORAMODIFICACION=CONVERT(CHAR(8),GETDATE(),108)
    WHERE IDVENTA=@Id;
    IF @DetalleJson IS NOT NULL
        EXEC dbo.usp_venta_guardar_detalle @Id, @DetalleJson;
    SET @Resultado=1; SET @Mensaje='Venta actualizada.';
END;
GO

IF OBJECT_ID('dbo.usp_venta_eliminar','P') IS NOT NULL DROP PROCEDURE dbo.usp_venta_eliminar;
GO
CREATE PROCEDURE dbo.usp_venta_eliminar @Id NVARCHAR(50), @Resultado INT OUTPUT, @Mensaje NVARCHAR(200) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE COTIZACION SET IDVENTA=NULL, ESTADO='Cotizado' WHERE IDVENTA=@Id;
    DELETE FROM VENTA_DETALLE WHERE IDVENTA=@Id;
    DELETE FROM VENTA WHERE IDVENTA=@Id;
    SET @Resultado=1; SET @Mensaje='Venta eliminada.';
END;
GO

PRINT 'SPs cotización y venta listos.';
GO
