/* Incremental: foto Base64 en producto + cliente libre en cotización/venta */
SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
GO

IF COL_LENGTH('dbo.PRODUCTO', 'FOTO') IS NULL
    ALTER TABLE dbo.PRODUCTO ADD FOTO NVARCHAR(MAX) NULL;
GO

IF COL_LENGTH('dbo.COTIZACION', 'NOMBRECLIENTE') IS NULL
    ALTER TABLE dbo.COTIZACION ADD NOMBRECLIENTE NVARCHAR(200) NULL;
GO

IF COL_LENGTH('dbo.VENTA', 'NOMBRECLIENTE') IS NULL
    ALTER TABLE dbo.VENTA ADD NOMBRECLIENTE NVARCHAR(200) NULL;
GO

DECLARE @sql NVARCHAR(MAX);
SELECT @sql = STRING_AGG('ALTER TABLE '+QUOTENAME(OBJECT_SCHEMA_NAME(fk.parent_object_id))+'.'+QUOTENAME(OBJECT_NAME(fk.parent_object_id))+' DROP CONSTRAINT '+QUOTENAME(fk.name), ';')
FROM sys.foreign_keys fk
JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id = fk.object_id
JOIN sys.columns c ON c.object_id = fkc.parent_object_id AND c.column_id = fkc.parent_column_id
WHERE c.name = 'IDCLIENTE' AND OBJECT_NAME(fk.parent_object_id) IN ('COTIZACION','VENTA');
IF @sql IS NOT NULL EXEC sp_executesql @sql;
GO

ALTER TABLE dbo.COTIZACION ALTER COLUMN IDCLIENTE NVARCHAR(50) NULL;
ALTER TABLE dbo.VENTA ALTER COLUMN IDCLIENTE NVARCHAR(50) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_COTIZACION_CLIENTE')
    ALTER TABLE dbo.COTIZACION ADD CONSTRAINT FK_COTIZACION_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES dbo.CLIENTE(IDCLIENTE);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_VENTA_CLIENTE')
    ALTER TABLE dbo.VENTA ADD CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES dbo.CLIENTE(IDCLIENTE);
GO

UPDATE dbo.COTIZACION SET NOMBRECLIENTE = c.NOMBRE
FROM dbo.COTIZACION q INNER JOIN dbo.CLIENTE c ON c.IDCLIENTE = q.IDCLIENTE
WHERE q.NOMBRECLIENTE IS NULL;
UPDATE dbo.VENTA SET NOMBRECLIENTE = c.NOMBRE
FROM dbo.VENTA v INNER JOIN dbo.CLIENTE c ON c.IDCLIENTE = v.IDCLIENTE
WHERE v.NOMBRECLIENTE IS NULL;

UPDATE dbo.COTIZACION SET ESTADO = 'Cotizado' WHERE ESTADO IN ('Borrador');
UPDATE dbo.COTIZACION SET ESTADO = 'Enviado' WHERE ESTADO IN ('Enviada');
UPDATE dbo.COTIZACION SET ESTADO = 'Aceptado' WHERE ESTADO IN ('Aceptada');
GO

PRINT 'Columnas foto y cliente libre listas.';
GO
